import { readFileSync } from 'fs';

const sheet = readFileSync('js/character-sheet.js', 'utf8');
const site = readFileSync('js/site-identity.js', 'utf8');
const index = readFileSync('index.php', 'utf8');

function must(cond, msg) {
  if (!cond) throw new Error(msg);
}

must(site.includes("Vadania's Trailbook"), 'missing Vadania title');
must(site.includes("Brawn's Brawlbook"), 'missing Brawn title');
must(site.includes("Puck's Surgebook"), 'missing Puck title');
must(site.includes("Blingus's Bardbook"), 'missing Blingus title');
must(site.includes("lockCharacter: 'blingus'"), 'blingus must lock to himself');
must(site.includes('function applyTheme'), 'class palettes must follow the active character');
must(site.includes('function fxEnabled'), 'FX toggle helper present');
must(site.includes('blingus-fx-toggle'), 'FX toggle notifies the effect layers');
must(index.includes('id="partyFxBtn"'), 'toolbar has an FX toggle');
must(site.includes('book-bruck'), 'brawn uses the dwarf/monk book class');
must(sheet.includes('lockedCharacterId'), 'sheet must honor site lock');
must(sheet.includes('if (guessed && guessed !== activeId && !lockedCharacterId())'), 'import must not unlock site');
must(index.includes('site-identity.js'), 'index must load site-identity');
must(index.includes('puck-fx.js'), 'puck wild-magic fx must load');
const styles = readFileSync('styles.css', 'utf8');
must(styles.includes('body.vadania-book'), 'vadania book tint');
must(styles.includes('body.brawn-book'), 'brawn book tint');
must(styles.includes('.party-fx-layer'), 'shared party fx layer');
must(styles.includes('body.book-blingus'), 'bard palette');
must(styles.includes('body.book-vadania'), 'ranger palette');
must(styles.includes('body.book-bruck'), 'monk palette');
must(styles.includes('body.book-puck'), 'sorcerer palette');
must(styles.includes('ᛒ ᚱ ᚨ ᚹ ᚾ'), 'brawn banner runes');
must(index.includes('class="book-'), 'PHP must stamp the book palette class');
must(index.includes('vadania-fx.js'), 'vadania ranger fx must load');
must(index.includes('brawn-fx.js'), 'brawn monk fx must load');
const puckFx = readFileSync('js/puck-fx.js', 'utf8');
must(puckFx.includes('blingus-character-change'), 'puck fx follows the active character');
must(puckFx.includes('prefers-reduced-motion'), 'puck fx honors reduced motion');
must(puckFx.includes("locked === 'puck'"), 'puck fx stays off other party books');
must(puckFx.includes('blingus-fx-toggle'), 'puck fx honors the FX toggle');
const vadaniaFx = readFileSync('js/vadania-fx.js', 'utf8');
must(vadaniaFx.includes('blingus-character-change'), 'vadania fx follows the active character');
must(vadaniaFx.includes('prefers-reduced-motion'), 'vadania fx honors reduced motion');
must(vadaniaFx.includes("locked === 'vadania'"), 'vadania fx stays off other party books');
must(vadaniaFx.includes('blingus-fx-toggle'), 'vadania fx honors the FX toggle');
must(vadaniaFx.includes("kind: 'peek'"), 'vadania critters peek from the edge');
must(vadaniaFx.includes("kind: 'arrow'"), 'vadania arrows fly across');
const brawnFx = readFileSync('js/brawn-fx.js', 'utf8');
must(brawnFx.includes('blingus-character-change'), 'brawn fx follows the active character');
must(brawnFx.includes('prefers-reduced-motion'), 'brawn fx honors reduced motion');
must(brawnFx.includes("locked === 'bruck'"), 'brawn fx stays off other party books');
must(brawnFx.includes('blingus-fx-toggle'), 'brawn fx honors the FX toggle');
must(brawnFx.includes("kind: 'fist'"), 'brawn punches with fists');
must(brawnFx.includes("kind: 'rune'"), 'brawn fx includes dwarven runes');
must(brawnFx.includes('RUNE_STROKES'), 'brawn runes are drawn glyphs');
must(brawnFx.includes('rand(58, 78)'), 'brawn fists must be large enough to read');
must(brawnFx.includes("kind: 'ring'"), 'brawn punches leave impact rings');
must(index.includes('$blingusSites'), 'index must brand from Host');
must(index.includes("'lockCharacter' => 'vadania'"), 'vadania must lock in PHP');
must(index.includes('$showKaraoke'), 'index must hide karaoke on non-bard hosts');
must(index.includes('data-section="classLines"'), 'class lines tab in index');
must(index.includes('class-lines-data.js'), 'class lines data must load');
must(sheet.includes('hasClassLines'), 'class lines helper present');
must(sheet.includes('namedNonBard'), 'named non-bards cannot keep bard karaoke');
const classLines = readFileSync('js/data/class-lines-data.js', 'utf8');
must(classLines.includes("Hunter's Mark"), 'ranger marks catalog');
must(classLines.includes('Flurry of Blows'), 'monk focus catalog');
must(classLines.includes('Wild Surge'), 'sorcerer surge catalog');
must(classLines.includes("Hunter's Patience"), 'ranger catalog has trail patience');
must(classLines.includes('Pass without Trace'), 'ranger catalog has pass without trace');
must(classLines.includes('Crown of Remembrance'), 'monk catalog has the crown');
must(classLines.includes('Educational'), 'monk catalog has educational fist');
must(classLines.includes('Chaos Bolt'), 'sorcerer catalog has chaos bolt');
must(classLines.includes('Fairy Magic'), 'sorcerer catalog has fairy magic');
must(classLines.includes('Innate Sorcery'), 'sorcerer catalog has innate sorcery');
must(!classLines.includes('Vicious Mockery'), 'class lines are not bard spell karaoke');
function classLineCount(block) {
  return (block.match(/classLine\(/g) || []).length;
}
const rangerBlock = classLines.match(/ranger: \{[\s\S]*?\n  monk:/);
const monkBlock = classLines.match(/monk: \{[\s\S]*?\n  sorcerer:/);
const sorcererBlock = classLines.match(/sorcerer: \{[\s\S]*?\n\};/);
must(rangerBlock && classLineCount(rangerBlock[0]) >= 70, 'ranger marks should approach bardic depth');
must(monkBlock && classLineCount(monkBlock[0]) >= 70, 'monk focus should approach bardic depth');
must(sorcererBlock && classLineCount(sorcererBlock[0]) >= 70, 'sorcerer surges should approach bardic depth');
must(sheet.includes("hasClass('bard'"), 'bard karaoke gate present');
must(sheet.includes('visibleSections'), 'class tabs present');
must(sheet.includes("item('Hunter\\'s Mark'") || sheet.includes('Hunter\'s Mark'), 'vadania ranger spells');
must(sheet.includes("item('Unarmed Strike'"), 'brawn monk kit');
must(sheet.includes("item('Chaos Bolt'"), 'puck sorcerer spells');
must(sheet.includes('getSkillNames'), 'skill chips must follow the sheet');
must(sheet.includes('getClassCombatOptions'), 'class features must become combat chips');
must(sheet.includes("item('Hunting Knife'"), 'vadania needs a backup blade');
must(sheet.includes("item('Crystal focus'"), 'puck needs a sorcerer focus');
const vadaniaFn = sheet.match(/function defaultVadania\(\) \{[\s\S]*?\n  function defaultBruck/);
must(vadaniaFn, 'defaultVadania missing');
must(!vadaniaFn[0].includes('Vicious Mockery'), 'vadania must not inherit bard mockery');
must(vadaniaFn[0].includes('Survival'), 'vadania ranger skills');
must(sheet.includes('PLACEHOLDER SHEET'), 'placeholder sheets must label themselves');
must(vadaniaFn[0].includes('placeholderNotes'), 'vadania uses placeholder notes');
must(vadaniaFn[0].includes('dex: 16'), 'vadania placeholder DEX');
must(vadaniaFn[0].includes("spellKind: 'save'"), 'vadania spells carry kinds for Cast chips');
const bruckFn = sheet.match(/function defaultBruck\(\) \{[\s\S]*?\n  function defaultPuck/);
must(bruckFn, 'defaultBruck missing');
must(bruckFn[0].includes('placeholderNotes'), 'brawn uses placeholder notes');
must(bruckFn[0].includes('Unarmed Strike'), 'brawn monk weapons');
must(bruckFn[0].includes('hpMax: 43'), 'brawn placeholder HP');
must(!bruckFn[0].includes('Vicious Mockery'), 'brawn must not inherit bard mockery');
const puckFn = sheet.match(/function defaultPuck\(\) \{[\s\S]*?\n  function defaultCharacter/);
must(puckFn, 'defaultPuck missing');
must(puckFn[0].includes('placeholderNotes'), 'puck uses placeholder notes');
must(puckFn[0].includes('cha: 17'), 'puck placeholder CHA');
must(puckFn[0].includes("spellKind: 'attack'"), 'puck spells carry kinds for Cast chips');
must(sheet.includes('abilitiesAreEmpty'), 'empty stub scores must hydrate');
must(sheet.includes('combatNeedsPlaceholder'), 'empty stub HP must hydrate');
must(sheet.includes('namedNonBard,'), 'namedNonBard must be exported for workflow');
must(sheet.includes('isBlingusShaped'), 'named books must reject a Blingus-shaped stored sheet');
must(sheet.includes('acceptsRemoteSheet'), 'named books must reject the shared Blingus server sheet');

const workflow = readFileSync('js/action-workflow.js', 'utf8');
must(workflow.includes('getClassCombatOptions'), 'workflow must offer class combat extras');
must(workflow.includes("Crown of Remembrance"), 'brawn crown is a situation chip');
must(workflow.includes('kitOnlyMode'), 'locked sites must not dump the PHB weapon list');
must(workflow.includes('namedNonBard'), 'named books stay kit-only even without a Host lock');
must(sheet.includes('hasSongbook'), 'non-bards get a general songbook');
must(index.includes("data-section=\"songs\""), 'karaoke songs tab in index');

const songbook = readFileSync('js/data/songs-data.js', 'utf8');
must(songbook.includes("Don't Stop Believin'"), 'songbook has general tracks');
must(!songbook.includes('Vicious Mockery'), 'songbook must not be spell parodies');

must(workflow.includes('getSkillNames()'), 'workflow skills must come from the sheet');
must(workflow.includes("id: 'trailCall'"), 'ranger trail call chip');
must(workflow.includes("id: 'focus'"), 'monk focus chip');
must(workflow.includes("id: 'surge'"), 'sorcerer surge chip');
must(workflow.includes("id: 'paulHarvey'"), 'blingus paul harvey chip');
must(workflow.includes("id: 'productPlacement'"), 'blingus product placement chip');
must(workflow.includes("id: 'pharmaAd'"), 'blingus pharma ad chip');
must(workflow.includes("id: 'confessional'"), 'blingus confessional chip');
must(workflow.includes("id: 'cliffhanger'"), 'blingus cliffhanger chip');
must(workflow.includes("id: 'standup'"), 'blingus standup chip');
must(workflow.includes("id: 'roast'"), 'roast chip');
must(workflow.includes("id: 'troyMcClure'"), 'blingus troy mcclure chip');
must(workflow.includes("id: 'showtime'"), 'blingus showtime chip');
must(workflow.includes("id: 'closer'"), 'blingus closer chip');
must(workflow.includes("id: 'inspiration'"), 'bard inspiration chip');
must(workflow.includes("id: 'songOfRest'"), 'bard song of rest chip');
must(workflow.includes("id: 'healBuff'"), 'heal/buff chip');
must(workflow.includes("id: 'flirt'"), 'flirt chip');
must(workflow.includes("id: 'graffiti'"), 'graffiti chip');
must(workflow.includes("id: 'travelBanter'"), 'travel banter chip');
must(workflow.includes("id: 'rally'"), 'rally chip');
must(workflow.includes("id: 'downed'"), 'last breath chip');
must(workflow.includes("id: 'eulogy'"), 'eulogy chip');
must(workflow.includes("id: 'yelpReview'"), 'yelp review chip');
must(workflow.includes("id: 'previouslyOn'"), 'previously on chip');
must(workflow.includes("id: 'natureDoc'"), 'nature doc chip');
must(workflow.includes('Focus up'), 'monk motivation chip');
must(workflow.includes('Steady the line'), 'ranger motivation chip');
must(workflow.includes('Ride the surge'), 'sorcerer motivation chip');
must(workflow.includes('SITUATION_BY_CLASS'), 'situation chips are class-based');
must(workflow.includes('function lineFitsSpeaker'), 'non-bards must drop bard scene voice');
must(workflow.includes('BARD_VOICE_RE'), 'bard scene voice has a filter');
must(workflow.includes('years of bardic'), 'filter catches bardic training lines');
must(sheet.includes("modId === 'trailCall'"), 'trailCall gated to ranger');
must(sheet.includes("modId === 'focus'"), 'focus gated to monk');
must(sheet.includes("modId === 'surge'"), 'surge gated to sorcerer');
must(sheet.includes("modId === 'paulHarvey'"), 'paul harvey gated to blingus');
must(sheet.includes('PARTY_CLASS'), 'named party classes cannot stay bard');
must(sheet.includes("modId === 'introduction')") || sheet.includes("id !== 'blingus' && PARTY_CLASS[id]"), 'named non-bards cannot keep bard speech chips');

const voice = readFileSync('js/outcome-generate.js', 'utf8');
must(voice.includes('DEFAULT_PERSONALITY_VADANIA'), 'vadania personality');
must(voice.includes('DEFAULT_PERSONALITY_BRUCK'), 'brawn personality');
must(voice.includes('DEFAULT_PERSONALITY_PUCK'), 'puck personality');
must(voice.includes("STORAGE_KEY + ':' + who"), 'personality storage is per character');
must(voice.includes('Write as Vadania, not as Blingus'), 'vadania must refuse Blingus voice');
must(voice.includes('Bo is an NPC, not a PC'), 'blingus default treats Bo as NPC');
must(voice.includes('Bo is the NPC who brought you together'), 'other PCs treat Bo as NPC');
must(voice.includes('Write as Brawn, not as Blingus'), 'brawn must refuse Blingus voice');
must(voice.includes('Oh well!'), 'brawn has the indifferent oh-well shrug');
must(voice.includes('STALE_PERSONALITY_BRUCK_PRE_OH_WELL'), 'brawn default migrates to oh-well bit');
must(voice.includes('Write as Puck, not as Blingus'), 'puck must refuse Blingus voice');
must(voice.includes('Fairy-twin insult bit with Puck'), 'blingus has puck impersonation insult bit');
must(voice.includes('Fairy-twin insult bit with Blingus'), 'puck has blingus impersonation insult bit');
must(voice.includes('STALE_PERSONALITY_PRE_FAIRY_INSULT'), 'blingus default migrates to fairy-twin insult bit');
must(voice.includes('STALE_PERSONALITY_PUCK_PRE_FAIRY_INSULT'), 'puck default migrates to fairy-twin insult bit');
must(voice.includes('speakerId:'), 'generate must send speakerId');
must(voice.includes('function personalityOwner'), 'stored personality must know which speaker it belongs to');
must(voice.includes('if (owner && owner !== who)'), 'wrong-speaker personality must reset to this book');
must(voice.includes('function moodsFor'), 'moods are per character');
must(voice.includes('function defaultMoodId'), 'each book has its own default mood');
must(voice.includes('Watchful'), 'vadania playful mood is Watchful');
must(voice.includes('Night journal'), 'vadania melancholy is journal voice');
must(voice.includes('Scorched'), 'vadania paranoid is Scorched trust');
must(voice.includes('Old stone'), 'brawn melancholy is Old stone');
must(voice.includes('Weave-twitchy'), 'puck paranoid is weave-twitchy');
must(voice.includes('Naughty fey'), 'puck lewd is Naughty fey');
must(voice.includes('his royal nobleness'), 'blingus default names Talavar that way');
must(voice.includes('Glim the goblin'), 'blingus default keeps the pizza-goblin tale');
must(voice.includes('journal-steady'), 'vadania voice is the November journal');
must(voice.includes('Trust scorched away'), 'vadania default keeps the Loomlurch wound');
must(voice.includes('Do not name who cast it'), 'vadania must not pin the ray');
must(voice.includes('Do not confess the Loomlurch Scorching Ray'), 'puck must not confess the ray');
must(voice.includes('a Fist and Fortitude'), 'brawn default keeps the sundial answers');
must(voice.includes("bruck: 'deadpan'"), 'brawn default mood is Flat');
must(voice.includes("puck: 'manic'"), 'puck default mood is Surge');

const app = readFileSync('script.js', 'utf8');
must(app.includes('function applyLoadedCharacter'), 'server load must not stamp one sheet onto every book');
must(app.includes('api.acceptsRemoteSheet'), 'server character apply is gated');
must(app.includes("=== 'blingus'"), 'only Blingus may write the shared character blob');
must(app.includes('data.personalities'), 'server save must keep a personalities map');
must(app.includes("who === 'blingus' ? shared"), 'shared personality blob is Blingus-only');

const dataApi = readFileSync('api/blingus-data.php', 'utf8');
must(dataApi.includes('array_merge($prevRoster, $incomingRoster)'), 'server roster merge must not wipe Blingus');
must(dataApi.includes("$data['personalities']"), 'server must merge personalities like sheets');

const api = readFileSync('api/generate-outcome.php', 'utf8');
must(api.includes('$speakerId'), 'api must know who is speaking');
must(api.includes('NPC who brought the party together'), 'api Bo flavor is NPC');
must(api.includes('Fairy-twin insult bit'), 'api knows the puck/blingus impersonation roast');
must(api.includes('$meanwhileHabits'), 'api must idle in the speaker\'s habits');
must(api.includes("'trailCall'"), 'api allows ranger trail call');
must(api.includes("'focus'"), 'api allows monk focus');
must(api.includes("'surge'"), 'api allows sorcerer surge');
must(api.includes("'paulHarvey'"), 'api allows paul harvey');
must(api.includes("'pharmaAd'"), 'api allows pharma ad');
must(api.includes("'cliffhanger'"), 'api allows cliffhanger');
must(api.includes("'travelBanter'"), 'api allows travel banter');
must(api.includes("'eulogy'"), 'api allows eulogy');
must(api.includes('and now you know the rest of the story'), 'api paul harvey rule');
must(api.includes('ask-your-cleric'), 'api pharma ad rule');
must(api.includes('them Wayfarer kids'), 'api cliffhanger handle');
must(!api.includes("$isBlingus = ($speakerId === '' || $speakerId === 'blingus')"), 'empty speaker must not default to Blingus');
must(api.includes('Trust scorched, not a bit'), 'api vadania flavor is journal-scorched');
must(api.includes('Do not invent that he cast the Loomlurch Scorching Ray'), 'api puck flavor must not pin the ray');
must(api.includes('a Fist / Fortitude'), 'api brawn flavor keeps the sundial');
must(api.includes('Oh well!'), 'api brawn oh-well shrug');
must(api.includes('$classSpeechRule'), 'bard speech rules must be outcome-gated');
must(api.includes('$bardSceneBan'), 'non-bards must not get bard scene voice from Claude');
must(api.includes('skipped rehearsal'), 'api bans skipped-rehearsal voice off Blingus');
must(!api.includes('If a Situation / intent is set (Busking, Haggling, Hovering nearby'), 'roleplay prompt must not hardcode bard situations');

console.log('smoke-site: ok');
