"""Wittier critical hit/fail templates with Blingus voice."""

CRIT_FAIL_TEMPLATES = {
    'Polearms': [
        'My polearm catches on {overhead_snag} with theatrical commitment, leaving me exposed',
        'I misjudge the reach in {place} and overextend like I confused a joust with a dance number',
        'My polearm tangles with {ally_tangle} and we share an awkward moment nobody will forget',
        'I swing too wide and snag {snag_behind} behind me—the room hears the clang',
        'I trip on {floor_hazard} in {place} and hit {miss_surface} like a dropped prop',
        'The {light} in {place} hid {overhead_snag} until my polearm found it for everyone',
        'I thrust past my target and bury the point in {backstop}—wrong enemy, same confidence',
        'My polearm clatters off {terrain_nat} and throws me off balance in front of {who}',
    ],
    'Arrows': [
        'My arrow kisses {backstop} in {place} and vanishes into {miss_surface} like a bad metaphor',
        'I fumble the draw and send the shot over their head in {where}—generous, useless',
        'My bowstring snaps on {overhead_snag} and the arrow dies mid-arc, tragically',
        'I misjudge the angle in {place} and decorate {snag_behind} instead of my foe',
        'My quiver catches {snag_behind} and the release goes wide with audience energy',
        'I loose too early in {place} and the arrow skitters across {miss_surface} for laughs',
        'The shot pins {backstop} in {where} while my target remains inconveniently alive',
        'I slip on {floor_hazard} and send the arrow into empty air—my wings do not help',
    ],
    'Crossbolts': [
        'My crossbolt jams, fires late, and clatters off {backstop} like bad timing',
        'I misalign the shot in {place} and the bolt skids across {miss_surface} to applause',
        'The bolt catches {overhead_snag} and drops straight down in {where}—gravity wins',
        'I overcrank the winch and send the bolt past them into {snag_behind}',
        'My bolt thunks into {backstop} in {place} with the energy of a critique',
        'I fumble the trigger in {where} and nearly introduce {ally_tangle} to crossbow dentistry',
        'The shot ricochets off {terrain_nat} in {place} and finds nothing living',
        'I bury the bolt in {backstop} in {where} and pretend that was cover fire',
    ],
    'Swords': [
        'My swing goes wide in {place} and nearly rewrites {ally_tangle} as a casualty',
        'I overextend in {where} and stumble, offering my back like a poorly blocked verse',
        'My blade catches {snag_behind} and sticks—I tug, the room watches',
        'I slip on {floor_hazard} and carve heroic nothing through the air in {place}',
        'My sword rings off {backstop} instead of flesh—metal laughs at me',
        'I misjudge the parry in {where} and flash wrist like I forgot the choreography',
        'Sparks fly off {terrain_nat} in {place} and my target remains unimpressed',
        'I swing into {overhead_snag} and the blade sticks fast—commitment, wrong target',
    ],
    'Knives': [
        'My dagger slips on {floor_hazard} in {place} and nearly edits my own fingers',
        'I throw too hard in {where} and the knife clatters off {backstop} like a heckler',
        'My sleeve catches {snag_behind} and I stumble into physical comedy',
        'The throw lands handle-first on {miss_surface} in {place}—stylish failure',
        'My grip fails in {where} and the dagger spins toward {ally_tangle} by accident',
        'I fumble the draw in {place} and drop the blade at my feet—subtle',
        'The knife sails over their head in {where} and nests in {snag_behind}',
        'I slip in {place} and the knife skitters across {miss_surface} like stage fright',
    ],
    'Blunt Weapons': [
        'I swing too hard in {place}, lose balance on {floor_hazard}, and audition for slapstick',
        'My mace kisses {snag_behind} and wrenches my shoulder—wrong percussion',
        'I overextend in {where} and the blow bounces off armor with a dull, embarrassing thud',
        'My grip fails and the weapon spins toward {ally_tangle} like bad luck',
        'I trip in {place} and my mace thuds into {miss_surface}—impact without plot',
        'The swing hits {backstop} in {where} with a clang that says "not today"',
        'I clip {overhead_snag} in {place} and lose the rhythm entirely',
        'My follow-through sends me stumbling into {terrain_nat} in {where}',
    ],
    'Axes and Hammers': [
        'I swing too hard in {place} and my axe bites {backstop} instead of my foe',
        'My weapon catches {overhead_snag} and sticks—I look like I meant to decorate',
        'I overextend in {where} and bounce off armor with the charm of a wet drum',
        'My grip slips on {floor_hazard} and the axe nearly flies free for drama',
        'I trip in {place} and carve a useless groove in {miss_surface}',
        'The hammer hits {terrain_nat} in {where} and jars my arms and my pride',
        'I misjudge the swing in {place} and clip {snag_behind} instead of evil',
        'My axe rings off {backstop} in {where} and leaves me off balance and audible',
    ],
    'Other Weapons': [
        'My weapon slips in {place} and tumbles across {miss_surface} like a bad exit',
        'I fumble the attack in {where} and hit {backstop} instead of my foe—creative',
        'My grip fails mid-swing in {place} and the weapon spins wrong',
        'I trip on {floor_hazard} and carve through empty air in {where} with confidence',
        'My weapon snags on {snag_behind} and refuses to come free—awkward pause',
        'I misjudge the angle in {place} and the strike goes wide for everyone to see',
        'The blow clatters off {terrain_nat} in {where} with no effect and full shame',
        'I catch {overhead_snag} in {place} and lose the rhythm like a missed cue',
    ],
    'Fire': [
        'My fire spell fizzles in {place}, leaving warm air and my dignity smoking',
        'I misaim in {where} and scorch {backstop} instead of my target—close, wrong',
        'The flames die near {snag_behind} before reaching them—anticlimax with smoke',
        'My spell backfires in {place} and singes my own fingers—personal lesson',
        'The heat dies in {where} and {who} notice I brought a sparkler to a fight',
        'I lose concentration in {place} and the fire dies to harmless, judgmental sparks',
        'The blaze licks {overhead_snag} in {where} instead of my foe—dramatic misfire',
        'My flames gutter out on {floor_hazard} in {place} like a bad finale',
    ],
    'Cold': [
        'My ice magic produces a polite breeze in {place} instead of terror',
        'I mispronounce the word in {where} and the frost melts on {miss_surface}',
        'The cold backfires in {place} and numbs my fingers—ironic and inconvenient',
        'My freezing magic fails against the {light} in {where} like stage lights on snow',
        'I lose focus in {place} and the ice never forms—just my embarrassment',
        'The spell hits {backstop} in {where} and accomplishes nothing useful',
        'My frost sputters out near {snag_behind} in {place} with a sad hiss',
        'The chill dissipates in {where} before it reaches them—budget winter',
    ],
    'Lightning': [
        'My bolt fizzles into static in {place} and crackles like a bad sound check',
        'I misaim in {where} and the arc strikes {backstop} instead—wrong target, full voltage',
        'The lightning dies in {place} before crossing the gap—tragic underdelivery',
        'My spell backfires in {where} and shocks my own hand—note to self',
        'I lose concentration in {place} and only sparks remain, apologetic',
        'The bolt grounds into {terrain_nat} in {where} with no harm done to my foe',
        'My thunderous cast in {place} produces a pop worthy of a birthday candle',
        'Electricity flashes toward {overhead_snag} in {where} and fades, embarrassed',
    ],
    'Thunder': [
        'My thunder spell whispers in {place} when it should have headlined',
        'I misaim in {where} and the sonic blast rattles {backstop} only—loud, useless',
        'The sound dies in {place} before it reaches them—bad acoustics',
        'My ears ring in {where} from my own botched casting—self-inflicted encore',
        'I lose focus in {place} and the spell collapses like a deflated chorus',
        'The shockwave in {where} kicks dust on {miss_surface} and nothing else',
        'My voice cracks mid-incantation in {place} and the magic dies with it',
        'The thunder rolls toward {snag_behind} in {where} and fades, unconvincing',
    ],
    'Psychic': [
        'My psychic assault fizzles in {place}, leaving only a mild headache and mild shame',
        'I misaim in {where} and the mental push hits {backstop} instead of their mind',
        'The thought-blade dies in {place} before reaching them—bad telepathy day',
        'My own thoughts jumble in {where} and the spell collapses like bad lyrics',
        'I lose focus in {place} and they barely notice—rude and accurate',
        'The psychic wave in {where} scatters off {terrain_nat} and fades',
        'My concentration breaks in {place} and the magic unravels publicly',
        'The mental strike in {where} lands like a passive-aggressive suggestion',
    ],
    'Force': [
        'My force spell pushes only air in {place}—enthusiastic, ineffective',
        'I misaim in {where} and shove {backstop} instead of them—physics without payoff',
        'The magical pressure dies in {place} before landing—anticlimax in invisible font',
        'My spell backfires in {where} and pushes me a step backward—own goal',
        'I lose focus in {place} and the energy dissipates like a weak handshake',
        'The blast in {where} kicks dust across {miss_surface} and stops, politely',
        'My gesture falters in {place} and the force never coheres—bad dress rehearsal',
        'The push in {where} glances off {snag_behind} and fizzles with my ego',
    ],
    'Necrotic': [
        'My necrotic magic sputters in {place}, leaving a chill and my reputation intact',
        'I misaim in {where} and the decay licks {backstop} harmlessly—wrong corpse',
        'The dark energy dies in {place} before reaching them—underwhelming evil',
        'My spell backfires in {where} and my hands feel briefly wrong—career note',
        'I lose focus in {place} and the curse unravels like bad stitching',
        'The withering pulse in {where} fades against {terrain_nat}—nature shrugs',
        'My incantation slips in {place} and the magic collapses mid-menace',
        'The necrotic wave in {place} dissipates near {snag_behind}—failed mood',
    ],
    'Radiant': [
        'My radiant spell glows dimly in {place} like a candle at a rock concert',
        'I misaim in {where} and wash {backstop} with holy light—pretty, pointless',
        'The divine energy dies in {place} before striking true—faith, insufficient wattage',
        'My own eyes dazzle in {where} from my botched cast—self-inflicted halo',
        'I lose focus in {place} and the brilliance fades to awkward silence',
        'The beam in {where} scatters off {terrain_nat} and dies—bad angle',
        'My prayer stumbles in {place} and the magic unravels mid-verse',
        'The radiance in {where} flickers out near {snag_behind}—heaven declined',
    ],
    'Acid': [
        'My acid spell hisses out in {place}, leaving vapor and my confidence dissolved',
        'I misaim in {where} and the splash eats {backstop} without reaching them',
        'The corrosive bolt dies in {place} before landing—chemistry without commitment',
        'My fingers sting in {where} from my own botched casting—sour lesson',
        'I lose focus in {place} and the acid never forms—just my apology face',
        'The caustic spray in {where} patters harmlessly on {miss_surface}',
        'My gesture falters in {place} and the spell collapses mid-hiss',
        'The acid in {where} sizzles against {terrain_nat} and stops, unimpressive',
    ],
}

CRIT_HIT_TEMPLATES = {
    'Polearms': [
        'My polearm strikes in {place} with reach my target did not budget for',
        'I extend past their guard in {where} and drive the point home—sickening thud, satisfying story',
        'My weapon\'s length gives me the edge in {place} and the strike lands clean as a punchline',
        'A masterful thrust in {where} sends the tip through their defenses and my ego swells appropriately',
        'My polearm finds the gap in {light} and bites deep into my foe—chef\'s kiss',
        'I hook their guard in {place} and follow through with a crit worth humming about',
        'My reach in {where} keeps me safe while the blade still finds flesh—efficient violence',
        'The polearm strike in {place} connects with force my target will remember in therapy',
    ],
    'Arrows': [
        'My arrow finds its mark in {place}, sinking deep with a thud like a perfect downbeat',
        'I loose a shot in {where} that threads chaos and nails my target squarely—standing ovation optional',
        'My arrowhead buries in their flesh in {place} with brutal, artful precision',
        'The shot in {where} punches through leather and keeps going until it finds bone',
        'My arrow strikes true in {place}, tearing through fabric and doubt alike',
        'I capitalize on the opening in {where} and put the arrow exactly where it hurts',
        'The arrow in {place} lands with timing so clean it feels choreographed',
        'My shot in {where} finds the gap and my target staggers like the chorus hit',
    ],
    'Crossbolts': [
        'My bolt strikes in {place} with thunderous impact—bone splinters, narrative gold',
        'A perfectly aimed shot in {where} finds the gap between armor plates',
        'My crossbolt embeds in {place} with force enough to rewrite their posture',
        'The heavy projectile in {where} tears through their guard and keeps going',
        'My bolt strikes true in {place} and my foe crumples like a bad argument',
        'I drive the crossbolt home in {where} with precision and unreasonable confidence',
        'The shot in {place} connects cleanly—no one argues it was a crit',
        'My crossbolt in {where} finds flesh where armor failed and morale followed',
    ],
    'Swords': [
        'My blade cuts deep in {place}, drawing a line of crimson through their guard',
        'A masterful swing in {where} sends steel through defense with a ringing bite',
        'My sword strikes true in {place}, sparks flying like applause from metal',
        'I riposte in {where} so cleanly their weapon skitters away—embarrassing for them',
        'My blade opens a line across their guard in {place} and blood follows the melody',
        'The sword strike in {where} lands with deadly precision on my foe',
        'I capitalize on the opening in {place} and drive the hit home like a finale',
        'My sword in {where} finds the gap and my target reels from the blow',
    ],
    'Knives': [
        'My dagger cuts deep in {place}, sliding along bone with surgical spite',
        'My blade finds the gap in {where} and sinks in up to the hilt—small weapon, big statement',
        'A masterful throw in {place} sends my knife spinning into my target',
        'My dagger strikes true in {where}, doing outsized damage with fairy-sized flair',
        'I slip the knife between their ribs in {place} with a cruel, precise twist',
        'The throw in {where} embeds deep and my foe gasps on cue',
        'My knife in {place} lands with timing worth a slow clap',
        'I capitalize on the opening in {where} and drive the blade home',
    ],
    'Blunt Weapons': [
        'My mace strikes in {place} with bone-crushing force my target cannot shrug off',
        'A masterful swing in {where} sends my weapon through their guard like a crescendo',
        'My blunt weapon hits in {place} with thunderous force against my foe',
        'The blow in {where} shatters armor and bone alike—percussion section approved',
        'My strike in {place} sends them flying from the impact and my smirk',
        'I drive the mace home in {where} with brutal, efficient charm',
        'The crit in {place} connects cleanly—no one needs a second opinion',
        'My weapon in {where} finds flesh with devastating, story-worthy power',
    ],
    'Axes and Hammers': [
        'My axe cleaves in {place} with brutal force, leaving a wound and a memory',
        'A masterful swing in {where} sends the blade through their guard',
        'My hammer strikes in {place} with thunderous force against my target',
        'The heavy blow in {where} tears through layers of defense and dignity',
        'My weapon finds its mark in {place} with devastating power',
        'I drive the strike home in {where} and my foe spins from the impact',
        'The crit in {place} connects cleanly against my enemy—no notes',
        'My axe in {where} bites deep where armor failed and confidence followed',
    ],
    'Other Weapons': [
        'My weapon strikes in {place} with brutal force against my target—unexpected, effective',
        'An unconventional blow in {where} catches them off guard and lands hard',
        'My strike in {place} finds its mark with deadly, show-off precision',
        'I drive the attack home in {where} and my foe reels like a bad review',
        'The blow in {place} connects with devastating force and my grin',
        'My weapon in {where} lands with timing so good it feels unfair',
        'I capitalize on the opening in {where} and the crit lands clean',
        'The strike in {where} sends my target stumbling backward into legend',
    ],
    'Fire': [
        'Flames burst forth in {place} and wrap my target in searing, critique-level heat',
        'My fire spell in {where} detonates against my foe with explosive force',
        'Heat races across their body in {place}, leaving scorched trails and silence',
        'My flames in {where} find the gap in their armor and cling like a grudge',
        'The blaze in {place} erupts with crit force against my target',
        'I scorch them in {where} with a bloom of heat they cannot shrug off',
        'My fire strike in {place} lands with devastating, smoky precision',
        'The spell in {place} leaves my foe smoking, staggered, and memorable',
    ],
    'Cold': [
        'Frost erupts in {place} and locks my target in brutal, beautiful chill',
        'My ice magic in {where} bites deep through their defenses',
        'Cold spreads across them in {place} with crit force and rattling teeth',
        'The freezing spell in {where} finds flesh and does not let go',
        'My frost in {place} lands with shattering, crystal-clear precision',
        'Ice crawls over my target in {where} and leaves them gasping',
        'The cold strike in {where} connects with devastating force',
        'My spell in {where} leaves rime on their armor and pain beneath it',
    ],
    'Lightning': [
        'Lightning arcs in {place} and strikes my target with crackling, show-stopping force',
        'My bolt in {where} finds them and throws their muscles into spasm',
        'Electricity leaps in {place} and lands with crit precision and smoke',
        'The lightning in {where} sears through their guard like a spotlight',
        'My spell in {place} detonates against my foe in a flash worth remembering',
        'The bolt in {where} connects cleanly and leaves smoke in the air',
        'Thunder follows the strike in {place} as my target staggers',
        'My lightning in {where} lands with unmistakable crit force',
    ],
    'Thunder': [
        'A sonic blast in {place} hits my target like a hammer made of sound and spite',
        'My thunder spell in {where} erupts against my foe with crushing force',
        'The shockwave in {place} lands with crit precision on my target',
        'Sound becomes violence in {where} and my enemy reels',
        'My thunder in {place} connects with devastating force',
        'The blast in {where} rattles their bones and my crit lands clean',
        'I unleash sonic force in {where} and my target crumples',
        'The spell in {where} roars against my foe and leaves ears ringing',
    ],
    'Psychic': [
        'My psychic assault in {place} slams into their mind with crit force and bad dreams',
        'Mental blades in {where} find my target and leave them reeling',
        'The thought-strike in {place} lands with devastating, invasive precision',
        'I hammer their will in {where} and they stagger from the impact',
        'My spell in {place} burrows into their mind and does not miss',
        'Psychic force in {where} connects cleanly against my foe',
        'The assault in {place} leaves my target clutching their head and their dignity',
        'My mental strike in {where} lands with unmistakable crit power',
    ],
    'Force': [
        'A blast of force in {place} slams into my target with crit power and physics',
        'My spell in {where} hits them like an invisible battering ram with good timing',
        'Magical pressure in {place} finds my foe and throws them back',
        'The force strike in {where} connects with devastating precision',
        'I unleash raw magic in {place} and my target staggers',
        'The blast in {where} lands cleanly against my enemy',
        'My force spell in {where} hits with unmistakable crit impact',
        'Energy in {place} compresses against my foe and lands hard',
    ],
    'Necrotic': [
        'Dark energy in {place} wracks my target with crit force and bad complexion',
        'My necrotic spell in {where} withers flesh where it lands',
        'Decay in {place} finds my foe and does not let go—rude and effective',
        'The curse in {where} connects with devastating precision',
        'My magic in {place} leaves my target gray, gasping, and memorable',
        'Necrotic power in {where} lands cleanly against my enemy',
        'The withering strike in {where} hits my foe with unmistakable force',
        'My spell in {place} eats at their strength and my crit lands clean',
    ],
    'Radiant': [
        'Holy light in {place} sears my target with crit brilliance and no subtlety',
        'My radiant spell in {where} finds my foe and burns bright',
        'Divine force in {place} lands with devastating, judgmental precision',
        'The beam in {where} connects against my enemy with crit power',
        'Radiance in {place} wraps my target and does not miss',
        'My spell in {where} leaves them dazzled, wounded, and reconsidering life choices',
        'The holy strike in {where} lands against my enemy with unmistakable force',
        'Light in {place} becomes a weapon and my crit connects clean',
    ],
    'Acid': [
        'Corrosive magic in {place} eats through armor and finds flesh—chemistry wins',
        'My acid spell in {where} splashes my target with crit force and hiss',
        'Caustic energy in {place} lands with devastating precision',
        'The acid in {where} finds my foe and hisses where it bites',
        'My spell in {place} leaves smoking trails on their gear and skin',
        'The splash in {where} connects cleanly against my enemy',
        'Acid in {place} lands with unmistakable crit impact',
        'My corrosive strike in {where} melts their guard and hurts what is beneath',
    ],
}
