"""Skill-accurate vocabulary and line templates for outcome generation."""

SKILLS = [
    'Acrobatics', 'Animal Handling', 'Arcana', 'Athletics', 'Deception',
    'History', 'Insight', 'Intimidation', 'Investigation', 'Medicine',
    'Nature', 'Perception', 'Performance', 'Persuasion', 'Religion',
    'Sleight of Hand', 'Stealth', 'Survival',
]

SCENE_TYPE = {
    'Village': 'social', 'Town Square': 'social', 'Tavern': 'social', 'Inn': 'social',
    'Market': 'social', 'Shop': 'social', 'Temple': 'social', 'Blacksmith': 'social',
    'Listening for Rumors': 'social',
    'Castle': 'adventure', 'Dungeon': 'dungeon', 'Ruins': 'adventure', 'Cave': 'dungeon',
    'Crypt': 'dungeon', 'Tower': 'adventure', 'Fort': 'adventure', 'Sewers': 'dungeon',
    'Mine': 'dungeon',
    'Forest': 'wilderness', 'Mountains': 'wilderness', 'Hills': 'wilderness',
    'Desert': 'wilderness', 'Jungle': 'wilderness', 'Plains': 'wilderness',
    'Swamp / Marsh': 'wilderness', 'Coast': 'wilderness', 'Tundra': 'wilderness',
    'Bad Weather': 'wilderness', 'Travelling / On the Trail': 'wilderness', 'Camp': 'wilderness',
    'Carnival / Feywild (Wild Beyond The Witchlight)': 'special',
}

SCENE_CONTEXT = {
    'Village': {'place': 'the village', 'who': 'villagers'},
    'Town Square': {'place': 'the town square', 'who': 'the crowd'},
    'Tavern': {'place': 'the tavern', 'who': 'patrons'},
    'Inn': {'place': 'the inn', 'who': 'guests'},
    'Market': {'place': 'the market', 'who': 'vendors'},
    'Shop': {'place': 'the shop', 'who': 'the shopkeeper'},
    'Temple': {'place': 'the temple', 'who': 'the clergy'},
    'Blacksmith': {'place': 'the forge', 'who': 'the blacksmith'},
    'Listening for Rumors': {'place': 'the rumor mill', 'who': 'loose-tongued locals'},
    'Castle': {'place': 'the castle', 'who': 'courtiers and guards'},
    'Dungeon': {'place': 'the dungeon', 'who': 'my companions'},
    'Ruins': {'place': 'the ruins', 'who': 'the party'},
    'Cave': {'place': 'the cave', 'who': 'the party'},
    'Crypt': {'place': 'the crypt', 'who': 'the party'},
    'Tower': {'place': 'the tower', 'who': 'the onlookers'},
    'Fort': {'place': 'the fort', 'who': 'soldiers'},
    'Sewers': {'place': 'the sewers', 'who': 'the party'},
    'Mine': {'place': 'the mine', 'who': 'the party'},
    'Forest': {'place': 'the forest', 'who': 'the party'},
    'Mountains': {'place': 'the mountains', 'who': 'the party'},
    'Hills': {'place': 'the hills', 'who': 'the party'},
    'Desert': {'place': 'the desert', 'who': 'the party'},
    'Jungle': {'place': 'the jungle', 'who': 'the party'},
    'Plains': {'place': 'the open plains', 'who': 'the party'},
    'Swamp / Marsh': {'place': 'the swamp', 'who': 'the party'},
    'Coast': {'place': 'the coast', 'who': 'fisherfolk'},
    'Tundra': {'place': 'the tundra', 'who': 'the party'},
    'Bad Weather': {'place': 'the storm', 'who': 'the party'},
    'Travelling / On the Trail': {'place': 'the trail', 'who': 'fellow travelers'},
    'Camp': {'place': 'camp', 'who': 'the party'},
    'Carnival / Feywild (Wild Beyond The Witchlight)': {
        'place': 'the carnival', 'who': 'ticket-holding strangers',
    },
}

# Shared keys per scene type — only skill-relevant nouns, never "gossip" in animal handling.
TYPE_NOUNS = {
    'social': {
        'place': 'the gathering',
        'where': 'here',
        'who': 'the locals',
        'light': 'lamplight',
        'animal': 'a skittish dog tied outside',
        'animal2': 'a merchant\'s pack mule',
        'treat': 'a handful of oats from my pack',
        'beast_trouble': 'a panicked horse in the street',
        'magic': 'a minor charm on a doorframe',
        'rune': 'ward scratches near the threshold',
        'ward': 'a faded protective sigil',
        'aura': 'a faint magical residue',
        'obstacle': 'a crowd between me and the door',
        'foothold': 'a crate edge',
        'lift': 'a stuck wagon wheel',
        'climb': 'a hayloft ladder',
        'gap': 'the space between carts',
        'lie': 'a harmless cover story',
        'mark': 'a nosy stranger',
        'relic': 'a family crest on the wall',
        'inscription': 'carved initials on a beam',
        'era': 'the last time trouble came through town',
        'subject': 'the person avoiding eye contact',
        'tell': 'the way their smile never reaches their eyes',
        'motive': 'what they are really after',
        'threat': 'a low promise of consequences',
        'leverage': 'what they stand to lose',
        'clue': 'mud on the floor where it should not be',
        'evidence': 'a scrap of paper in the trash',
        'hidden': 'a loose floorboard',
        'patient': 'someone with a nasty cut',
        'injury': 'a bleeding arm',
        'symptom': 'the feverish flush in their cheeks',
        'flora': 'local plants and fungi',
        'fauna': 'tracks in the dirt',
        'weather': 'rain on the way',
        'terrain_nat': 'the ground nearby',
        'hidden_thing': 'a purse changing hands too quickly',
        'noise': 'footsteps on the stair',
        'scent': 'cheap perfume and sweat',
        'audience': 'everyone pretending not to listen',
        'stage': 'the space near the hearth',
        'act': 'a quick verse and a bow',
        'negotiator': 'the person holding all the cards',
        'pitch': 'why helping us costs them nothing',
        'offer': 'a fair trade and a flattering word',
        'rite': 'the local blessing over bread and salt',
        'doctrine': 'the taboo everyone knows but never says',
        'shrine': 'a small idol by the door',
        'item': 'a coin purse',
        'pocket': 'my sleeve',
        'distraction': 'a dropped tankard',
        'shadow': 'the corner by the barrels',
        'guard': 'the bored lookout',
        'cover_stealth': 'the press of the crowd',
        'trail': 'wagon ruts leading out of town',
        'shelter': 'a dry barn loft',
        'forage': 'apples fallen in the orchard',
    },
    'adventure': {
        'place': 'the site',
        'where': 'this place',
        'who': 'my companions',
        'light': 'torchlight',
        'animal': 'a guard dog in the yard',
        'animal2': 'a hawk circling the battlements',
        'treat': 'dried meat from my ration',
        'beast_trouble': 'a spooked warhorse',
        'magic': 'an old enchantment in the stonework',
        'rune': 'sigils carved into the archway',
        'ward': 'a failing ward on the inner door',
        'aura': 'cold magic lingering in the air',
        'obstacle': 'a gap in a collapsed wall',
        'foothold': 'a protruding stone',
        'lift': 'a fallen beam',
        'climb': 'crumbling masonry',
        'gap': 'a broken battlement',
        'lie': 'a story about being expected guests',
        'mark': 'whoever is watching the gate',
        'relic': 'a faded banner',
        'inscription': 'names on a memorial stone',
        'era': 'the last major trouble here',
        'subject': 'the person who will not meet my eyes',
        'tell': 'the tension in their shoulders',
        'motive': 'what they stand to gain',
        'threat': 'what happens if they do not step aside',
        'leverage': 'what they cannot afford to lose',
        'clue': 'scuff marks on the flagstones',
        'evidence': 'something out of place',
        'hidden': 'a tapestry that hangs too straight',
        'patient': 'whoever took the worst of it',
        'injury': 'a deep slice along the ribs',
        'symptom': 'labored breathing after the climb',
        'flora': 'ivy creeping through cracked mortar',
        'fauna': 'bats in the upper hall',
        'weather': 'wind howling through the arrow slits',
        'terrain_nat': 'uneven courtyard stones',
        'hidden_thing': 'a latch behind the shield display',
        'noise': 'armor clinking two rooms away',
        'scent': 'old smoke and rust',
        'audience': 'nobles pretending not to stare',
        'stage': 'the center of the great hall',
        'act': 'a formal bow that almost passes for courtly',
        'negotiator': 'whoever controls access here',
        'pitch': 'why letting us pass avoids embarrassment',
        'offer': 'information they want in exchange for access',
        'rite': 'the oath sworn on a noble\'s blade',
        'doctrine': 'the order\'s rule about uninvited guests',
        'shrine': 'a chapel alcove off the corridor',
        'item': 'a letter of introduction',
        'pocket': 'my belt pouch',
        'distraction': 'a dropped gauntlet',
        'shadow': 'the space behind a pillar',
        'guard': 'whoever is on patrol nearby',
        'cover_stealth': 'a line of hanging tapestries',
        'trail': 'boot prints in the courtyard dust',
        'shelter': 'a side chamber out of the wind',
        'forage': 'cold rations and stale wine',
    },
    'dungeon': {
        'place': 'the depths',
        'where': 'down here',
        'who': 'the party',
        'light': 'flickering torchlight',
        'animal': 'a giant rat the size of a cat',
        'animal2': 'a spider clinging to the ceiling',
        'treat': 'a bit of dried fish',
        'beast_trouble': 'a cornered cave fisher',
        'magic': 'a trapped glyph on the floor',
        'rune': 'symbols scratched near the arch',
        'ward': 'a warding circle half scrubbed away',
        'aura': 'sour magic around the iron door',
        'obstacle': 'a pit trap covered with canvas',
        'foothold': 'a narrow ledge',
        'lift': 'a portcullis chain',
        'climb': 'wet stone rungs',
        'gap': 'a chasm bridged by a rotting plank',
        'lie': 'a story about being maintenance workers',
        'mark': 'whoever has not spotted us yet',
        'relic': 'a rusted holy symbol',
        'inscription': 'warnings in a dead language',
        'era': 'when this place was last used',
        'subject': 'the person avoiding my gaze',
        'tell': 'the way their voice shakes on hard questions',
        'motive': 'what they are hiding',
        'threat': 'what happens if they raise the alarm',
        'leverage': 'what they thought was secret',
        'clue': 'chalk arrows on the wall',
        'evidence': 'something that does not belong here',
        'hidden': 'a brick that sounds hollow',
        'patient': 'whoever is hurt worst',
        'injury': 'a nasty wound that needs tending',
        'symptom': 'numbness spreading from the wound',
        'flora': 'pale fungus on the walls',
        'fauna': 'slime dripping from cracks',
        'weather': 'the damp cold that never lifts',
        'terrain_nat': 'slippery flagstones',
        'hidden_thing': 'a tripwire at ankle height',
        'noise': 'something dragging behind the next door',
        'scent': 'rot and ozone',
        'audience': 'nothing but echoing stone',
        'stage': 'the only flat ground before the altar',
        'act': 'a whispered song to keep courage up',
        'negotiator': 'whoever can unlock the next way forward',
        'pitch': 'why helping us helps them too',
        'offer': 'a fair trade for cooperation',
        'rite': 'the old prayer carved above the altar',
        'doctrine': 'the taboo written on the wall',
        'shrine': 'a defiled idol in the side chamber',
        'item': 'a rusted key',
        'pocket': 'the lining of my cloak',
        'distraction': 'a thrown pebble down the side tunnel',
        'shadow': 'the recess behind a broken statue',
        'guard': 'whoever is patrolling ahead',
        'cover_stealth': 'the darkness beyond torchlight',
        'trail': 'drag marks in the dust',
        'shelter': 'a side niche out of the draft',
        'forage': 'stale water seeping from a crack',
    },
    'wilderness': {
        'place': 'the wilds',
        'where': 'out here',
        'who': 'the party',
        'light': 'grey daylight',
        'animal': 'a wary deer at the treeline',
        'animal2': 'a pack mule that will not ford the stream',
        'treat': 'salt lick and calm words',
        'beast_trouble': 'a bear rummaging through our supplies',
        'magic': 'fey lights dancing over the marsh',
        'rune': 'standing stones covered in moss',
        'ward': 'old druid marks on the oak',
        'aura': 'wild magic thick in the air',
        'obstacle': 'a fallen log across the path',
        'foothold': 'a rocky outcrop',
        'lift': 'a boulder blocking the trail',
        'climb': 'a steep scree slope',
        'gap': 'a ravine we have to cross',
        'lie': 'a story about being licensed trappers',
        'mark': 'someone watching from cover',
        'relic': 'a cairn older than the kingdom',
        'inscription': 'weathered runes on the marker stone',
        'era': 'the last fight through here',
        'subject': 'the person whose story keeps shifting',
        'tell': 'the way they look at our packs',
        'motive': 'what they really want from us',
        'threat': 'what happens if they do not back down',
        'leverage': 'what they need more than we do',
        'clue': 'broken branches at shoulder height',
        'evidence': 'ashes still warm in the fire pit',
        'hidden': 'a snare line in the undergrowth',
        'patient': 'someone with heat exhaustion',
        'injury': 'a twisted ankle on the descent',
        'symptom': 'shivering that has nothing to do with rain',
        'flora': 'berries I recognize on sight',
        'fauna': 'wolf sign in the mud',
        'weather': 'a black line of storm on the horizon',
        'terrain_nat': 'the ridge we have to descend',
        'hidden_thing': 'a cave mouth hidden by brush',
        'noise': 'something large moving parallel to us',
        'scent': 'rain on pine and wet earth',
        'audience': 'only the party and the crows',
        'stage': 'the flat rock by the fire',
        'act': 'a marching song to keep feet moving',
        'negotiator': 'whoever claims this stretch of ground',
        'pitch': 'why sharing the camp beats bleeding',
        'offer': 'medicine they need for their hound',
        'rite': 'the old prayer for safe passage',
        'doctrine': 'the taboo about lighting fires on this hill',
        'shrine': 'a cairn with offerings of bone',
        'item': 'a flint and steel',
        'pocket': 'my boot cuff',
        'distraction': 'a bird call from the wrong direction',
        'shadow': 'the lee side of a boulder',
        'guard': 'whoever is watching from a distance',
        'cover_stealth': 'tall grass and failing light',
        'trail': 'prints leading toward the pass',
        'shelter': 'a rock overhang out of the wind',
        'forage': 'cattails and edible roots',
    },
    'special': {
        'place': 'the carnival',
        'where': 'this strange place',
        'who': 'onlookers',
        'light': 'impossible lantern glow',
        'animal': 'a pastel-colored goat with too many eyes',
        'animal2': 'a ticket-seller\'s trained raven',
        'treat': 'sugar from a rigged game booth',
        'beast_trouble': 'a fey hound that will not stop grinning',
        'magic': 'illusion magic woven through the banners',
        'rune': 'ticket numbers that rearrange when you blink',
        'ward': 'a boundary line drawn in glitter',
        'aura': 'magic that tastes like cotton candy',
        'obstacle': 'a carousel that spins the wrong direction',
        'foothold': 'the rim of a fortune-teller\'s stage',
        'lift': 'a prop strongman hammer',
        'climb': 'a rope ladder that lengthens itself',
        'gap': 'the space between two impossible tents',
        'lie': 'a story about being invited by Zybilna herself',
        'mark': 'the barker who knows too much',
        'relic': 'a ticket stub from yesterday that says tomorrow',
        'inscription': 'rules that rewrite themselves',
        'era': 'before the Witchlight broke the sky',
        'subject': 'the performer who is not sweating',
        'tell': 'the smile that shows too many teeth',
        'motive': 'what the carnival wants from us',
        'threat': 'what the ticket fine costs in memories',
        'leverage': 'the secret the ringmaster cannot afford',
        'clue': 'confetti that falls upward',
        'evidence': 'a contract written in laughter',
        'hidden': 'a door that only opens for losers',
        'patient': 'someone dizzy from fey wine',
        'injury': 'a burn that glows pink instead of red',
        'symptom': 'hiccups that sound like bells',
        'flora': 'flowers that turn to face only me',
        'fauna': 'fish swimming through the air',
        'weather': 'rain that falls in ribbons',
        'terrain_nat': 'the midway that shifts when I look away',
        'hidden_thing': 'a peephole into the backstage nowhere',
        'noise': 'calliope music from an empty booth',
        'scent': 'sugar smoke and thunder',
        'audience': 'a crowd that applauds at the wrong moments',
        'stage': 'the center ring under impossible lights',
        'act': 'a joke that makes the tent shiver',
        'negotiator': 'the ticket taker with starlight eyes',
        'pitch': 'why letting us through is funnier than stopping us',
        'offer': 'a song they have never heard in this world',
        'rite': 'the oath you swear on a golden ticket',
        'doctrine': 'the carnival rule about unpaid debts',
        'shrine': 'a booth labeled miracles for sale',
        'item': 'a loaded die',
        'pocket': 'my hat',
        'distraction': 'a burst of confetti from nowhere',
        'shadow': 'the space behind the mirror maze',
        'guard': 'a mime who blocks every path',
        'cover_stealth': 'the crowd watching the strongman act',
        'trail': 'ticket stubs leading toward the Big Top',
        'shelter': 'a tent that is bigger inside than out',
        'forage': 'food that tastes like childhood',
    },
}

SCENE_NOUN_OVERRIDES = {
    'Village': {
        'animal': 'the village dog',
        'animal2': 'a cow blocking the lane',
        'beast_trouble': 'the cow kicking at a fence post',
        'treat': 'a carrot from a villager\'s garden',
        'magic': 'a hedge witch\'s charm on the gate',
        'clue': 'fresh wagon tracks',
        'flora': 'herbs drying in the rafters',
        'fauna': 'chickens pecking in the yard',
        'terrain_nat': 'the muddy road',
    },
    'Town Square': {
        'animal': 'a guard dog tied to the notice board',
        'animal2': 'a merchant\'s pack mule at the curb',
        'beast_trouble': 'the mule kicking at a cart wheel',
        'audience': 'the whole square when the bell rings',
    },
    'Tavern': {
        'animal': 'the tavern cat dozing by the hearth',
        'animal2': 'the barkeep\'s old hound under a table',
        'treat': 'scraps from a patron\'s plate',
        'beast_trouble': 'a spooked mule at the stable door',
        'magic': 'a faint enchantment on the tapped keg',
        'rune': 'chalk marks behind the bar',
        'hidden_thing': 'the card cheat palming chips',
        'audience': 'everyone who pretends they are not listening',
        'stage': 'the space in front of the hearth',
        'negotiator': 'whoever is running the place',
        'shadow': 'the corner booth in the back',
        'flora': 'herbs hanging behind the bar',
        'fauna': 'rats in the cellar',
        'terrain_nat': 'the sawdust-strewn floor',
    },
    'Inn': {
        'animal': 'the inn cat stalking a mouse in the wall',
        'animal2': 'a guest\'s nervous riding horse in the stable',
        'beast_trouble': 'the horse kicking at its stall door',
        'noise': 'creaking floorboards above our room',
    },
    'Market': {
        'animal': 'a merchant\'s exotic bird in a cage',
        'animal2': 'a donkey overloaded with bolts of cloth',
        'evidence': 'a vendor\'s ledger left open too long',
        'flora': 'spices piled in open sacks',
        'fauna': 'pigeons fighting over dropped crumbs',
        'terrain_nat': 'the cobblestones between stalls',
    },
    'Shop': {
        'animal': 'a shop cat guarding the yarn shelves',
        'item': 'a trinket from the display',
        'negotiator': 'whoever owns the counter',
    },
    'Temple': {
        'animal': 'a temple cat that refuses to leave the altar rail',
        'animal2': 'a white dove kept in the courtyard',
        'rite': 'the blessing over incense and water',
        'doctrine': 'the order\'s rule about unsanctioned magic',
    },
    'Blacksmith': {
        'animal': 'the forge cat with singed whiskers',
        'animal2': 'a draft horse waiting to be shod',
        'scent': 'hot iron and coal smoke',
    },
    'Listening for Rumors': {
        'subject': 'the person talking too quietly',
        'clue': 'a detail repeated in different conversations',
        'hidden_thing': 'someone who stops talking when we get close',
    },
    'Castle': {
        'animal': 'a falcon on the lord\'s gauntlet',
        'animal2': 'a hound in the kennel yard',
        'negotiator': 'whoever decides who gets in',
        'audience': 'courtiers pretending to ignore us',
    },
    'Dungeon': {
        'animal': 'a giant rat the size of a cat',
        'animal2': 'a spider the size of a plate',
        'beast_trouble': 'a cornered cave fisher hissing in the dark',
        'magic': 'a trapped glyph humming on the floor',
        'hidden': 'a pressure plate disguised with dust',
    },
    'Ruins': {
        'animal': 'a sunning lizard on the rubble',
        'animal2': 'a hawk circling the broken tower',
        'beast_trouble': 'a snake coiled in the fallen masonry',
        'fauna': 'bats erupting from a cracked dome',
    },
    'Cave': {
        'animal': 'a bat knocked loose by our torch smoke',
        'animal2': 'a blind cave fish in the underground pool',
        'beast_trouble': 'a cornered cave fisher in the shallow water',
        'scent': 'damp stone and guano',
    },
    'Crypt': {
        'animal': 'a skeletal rat that should not still move',
        'aura': 'necromantic residue around the sarcophagus',
        'shrine': 'a defiled altar to a forgotten god',
    },
    'Tower': {
        'animal': 'a raven nesting in the arrow slit',
        'climb': 'the spiral stair with no railing',
        'noise': 'wind screaming through the murder holes',
    },
    'Fort': {
        'animal': 'a garrison dog that knows every officer by smell',
        'guard': 'the patrol on the palisade walk',
    },
    'Sewers': {
        'animal': 'a swarm of rats parting around our boots',
        'animal2': 'a crocodile nobody wanted to believe in',
        'scent': 'effluent and mildew',
    },
    'Mine': {
        'animal': 'a canary in a cage the foreman insists is decorative',
        'animal2': 'giant beetles in the collapsed tunnel',
        'hazard': 'a groaning timber support',
    },
    'Forest': {
        'animal': 'a deer frozen at the edge of our campfire light',
        'animal2': 'a wolf watching from the treeline',
        'fauna': 'squirrels going suddenly silent',
    },
    'Mountains': {
        'animal': 'a mountain goat on an impossible ledge',
        'climb': 'a cliff face with only finger-width holds',
    },
    'Hills': {
        'animal': 'sheep scattering across the ridge',
        'trail': 'a sheep path that cuts hours off the route',
    },
    'Desert': {
        'animal': 'a camel that refuses to kneel',
        'animal2': 'a sidewinder sliding away from our shade',
        'weather': 'heat that shimmers off the dunes',
    },
    'Jungle': {
        'animal': 'a capuchin monkey trying to steal my pack',
        'animal2': 'a brightly colored snake coiled on the branch',
        'flora': 'vines I know are safe to cut through',
    },
    'Plains': {
        'animal': 'a herd of wild horses crossing the horizon',
        'weather': 'a wall of thunderheads over the grassland',
    },
    'Swamp / Marsh': {
        'animal': 'a bullfrog chorus that stops when we move',
        'animal2': 'a mud-caked feral hog blocking the path',
        'terrain_nat': 'sucking mud disguised as solid ground',
    },
    'Coast': {
        'animal': 'a gull that steals food right from the dock',
        'animal2': 'a stranded seal pup drawing a crowd',
        'weather': 'tide and wind changing faster than expected',
    },
    'Tundra': {
        'animal': 'a arctic fox circling our camp at a distance',
        'weather': 'whiteout conditions rolling in',
        'shelter': 'a snow trench out of the wind',
    },
    'Bad Weather': {
        'weather': 'lightning striking close enough to taste',
        'shelter': 'the lee of a rock that might not be enough',
    },
    'Travelling / On the Trail': {
        'animal': 'a pack mule that suddenly will not move',
        'trail': 'fresh prints crossing our route',
    },
    'Camp': {
        'animal': 'a horse tied too close to the fire',
        'animal2': 'a raccoon already in our food stores',
        'shelter': 'the tent canvas rattling in the wind',
    },
    'Carnival / Feywild (Wild Beyond The Witchlight)': {
        'animal': 'a pastel goat with too many eyes',
        'magic': 'illusion magic in every banner and ticket stub',
    },
}

SKILL_TEMPLATES = {
    'Acrobatics': {
        'Success': [
            "I cross {obstacle} in {place} with a clean tumble and stick the landing",
            "I use {foothold} as a springboard and land exactly where I meant to",
            "I recover from a slip in {where} and make it look intentional",
            "I weave through {place} while {who} stare like it was choreographed",
            "I balance on {foothold} where nobody else could and hop down grinning",
            "I flip over {obstacle} in {place} and land on my feet without breaking stride",
            "I catch myself on {foothold} mid-fall and bow like that was the plan",
            "I move through {place} in half the time anyone expected, silent and steady",
        ],
        'Failure': [
            "I misjudge {obstacle} in {place} and hit the ground harder than intended",
            "My foot catches on {foothold} and I tumble in front of {who}",
            "I attempt a showy move in {place} and eat dirt instead",
            "I lose my balance on {obstacle} and crash into something loud",
            "My acrobatics fail me in {where} and the landing is undignified",
            "I try to look graceful on {foothold} and faceplant instead",
            "I slip on {obstacle} and take {who} down with me",
            "My leap in {place} falls short and everyone pretends not to notice",
        ],
    },
    'Animal Handling': {
        'Success': [
            "I approach {animal} in {place} with slow hands and a softer voice until it settles",
            "I offer {treat} and wait until {animal} takes it without biting",
            "I read fear in {animal2} before it spooks and adjust my movement in time",
            "I guide {animal} away from {beast_trouble} without anyone getting hurt",
            "I speak low and steady until {animal2} stops pacing and lies down",
            "I keep my body small and unthreatening near {animal} until trust wins out",
            "I calm {animal} in {place} well enough that {who} stop backing away",
            "I handle {animal2} exactly right and the immediate danger passes",
        ],
        'Failure': [
            "I move too fast and {animal} bolts straight into {beast_trouble}",
            "I misread {animal2} and nearly take a bite for my trouble",
            "I reach for {animal} too quickly and it lashes out",
            "I offer {treat} at the worst moment and make {animal} more agitated",
            "I miss how frightened {animal} looks and startle it badly",
            "My attempt with {animal2} in {place} turns into chaos",
            "I speak too loud near {animal} and every beast nearby panics",
            "I grab at {animal} at the wrong moment and lose its trust entirely",
        ],
    },
    'Arcana': {
        'Success': [
            "I recognize {aura} in {place} and know what spell left it",
            "I trace the pattern in {rune} and understand its purpose",
            "I identify the school of magic on {ward} before anyone touches it",
            "I read {magic} in {where} and warn {who} what not to do",
            "I sense the enchantment on {ward} and how to avoid triggering it",
            "I decode {rune} in {place} and piece together the caster's intent",
            "I spot unstable magic gathering around {magic} and know how to dispel it",
            "I name the components involved from {aura} alone",
        ],
        'Failure': [
            "The symbols on {rune} in {place} might as well be scribbles to me",
            "I misidentify {magic} in {where} and almost get us cursed",
            "I touch {ward} thinking it's harmless and learn otherwise",
            "I can't parse {aura} in {where} no matter how I squint",
            "My theory about {magic} is wrong and {who} pay for it",
            "I confuse two schools of magic on {rune} and give bad advice",
            "The enchantment on {ward} stays a mystery and keeps humming",
            "I misread {aura} in {place} and nearly trigger something worse",
        ],
    },
    'Athletics': {
        'Success': [
            "I haul myself up {climb} in {place} with strength to spare",
            "I push through {obstacle} in {where} when others hesitate",
            "I lift {lift} clear of {who} before anyone gets crushed",
            "I climb {climb} fast enough to beat the danger closing in",
            "I hold the line in {place} when the strain should break me",
            "I swim, climb, or sprint through {where} and don't quit",
            "I break {lift} free with brute force that finally works",
            "I leap {gap} in {place} and catch the far side cleanly",
        ],
        'Failure': [
            "My grip fails on {climb} and I slide back down in {place}",
            "I strain against {lift} and can't budge it an inch",
            "I misjudge {gap} in {where} and fall short",
            "My muscles give out in {place} at the worst possible moment",
            "I try to climb {climb} and slip, scraping hands and pride",
            "I overestimate my strength on {lift} and drop it",
            "I exhaust myself on {obstacle} and need {who} to pull me out",
            "I attempt the feat in {where} and fail loudly",
        ],
    },
    'Deception': {
        'Success': [
            "I sell {lie} in {place} with a straight face and perfect timing",
            "I invent a cover story in {where} that holds under quick scrutiny",
            "I misdirect {mark} using {distraction} as camouflage for the truth",
            "I play the part in {place} so well even I almost believe it",
            "I answer the hard question in {where} without a tell showing",
            "I weave {lie} around {mark} and send attention the wrong way",
            "I convince {mark} I'm someone I'm not, at least for now",
            "I redirect the conversation in {place} before anyone connects dots",
        ],
        'Failure': [
            "My story in {place} falls apart the moment someone asks a follow-up",
            "I stammer near {mark} and {who} know something's off",
            "I contradict {lie} in {where} and the deception collapses",
            "My nervous glance at {mark} gives everything away",
            "I try to bluff {mark} in {place} and get laughed at",
            "I forget a detail in {lie} and get caught cold",
            "My cover in {where} lasts about ten seconds",
            "I lie badly in {place} and make {who} more suspicious than before",
        ],
    },
    'History': {
        'Success': [
            "I recall exactly who ruled {place} and why that matters now",
            "I recognize {relic} and know the story behind it",
            "I connect {inscription} in {where} to {era} that {who} forgot",
            "I remember the old treaty that explains the tension in {place}",
            "I identify the era of {relic} from its craftsmanship alone",
            "I cite {era} and what went wrong the last time",
            "I know the legend tied to {inscription} and warn the party in time",
            "I translate {inscription} without guessing",
        ],
        'Failure': [
            "I swear I've read about {place} but can't recall a useful detail",
            "I misdate {relic} by centuries and {who} notice",
            "I confuse two wars and draw the wrong lesson in {where}",
            "The {inscription} might as well be gibberish to me",
            "I guess at who built {place} and guess wrong",
            "I mix up legends about {era} and steer us poorly",
            "I blank on the name {who} expected me to know",
            "I invent a historical fact about {relic} that gets corrected immediately",
        ],
    },
    'Insight': {
        'Success': [
            "I read {tell} from {subject} in {place} and know their real motive",
            "I catch {subject} smiling through a lie in {where}",
            "I notice how {subject} glances at {evidence} when the topic gets sensitive",
            "I understand {motive} in {subject} before it boils over",
            "I catch the micro-expression from {subject} that changes everything",
            "I realize {subject} is scared, not angry, and adjust my approach",
            "I see who in {who} is holding back the truth",
            "I hear {subject} hesitate and know the story doesn't fit",
        ],
        'Failure': [
            "I trust {subject} in {place} and miss the warning signs",
            "I read {subject} completely wrong in {where}",
            "I think {who} are friendly and walk into a setup",
            "I miss the fear behind the bravado from {subject}",
            "I assume honesty from {subject} in {place} and get played",
            "I misinterpret the silence from {subject} as agreement",
            "I don't notice the lie from {subject} until it's too late",
            "I misjudge {motive} in {where} and advise the party badly",
        ],
    },
    'Intimidation': {
        'Success': [
            "I lower my voice in {place} and {mark} reconsider immediately",
            "I make {threat} in {where} feel real without raising a hand",
            "I stare down {mark} until they step aside",
            "I use {leverage} as pressure and {who} back off",
            "I project enough menace in {place} that talk replaces action",
            "I convince {mark} I'm not bluffing about {beast_trouble}",
            "I turn the mood in {place} cold and get compliance",
            "I let silence do the work in {where} until {mark} breaks",
        ],
        'Failure': [
            "I try to intimidate {mark} in {place} and they laugh",
            "My {threat} in {where} lands like a joke",
            "I attempt menace near {mark} and look more annoyed than scary",
            "I bark orders in {place} and {who} ignore me",
            "I overplay the act in {where} and lose credibility",
            "I threaten {mark} who clearly isn't impressed",
            "My voice cracks in {place} at the worst moment",
            "I bluff about {leverage} and get called on it",
        ],
    },
    'Investigation': {
        'Success': [
            "I find {clue} in {place} that everyone else walked past",
            "I connect {evidence} to {hidden} and the picture clears",
            "I search {where} methodically and turn up what we need",
            "I notice what's missing in {place}, not just what's present",
            "I reconstruct events in {where} from {evidence} and timing",
            "I follow {clue} to {hidden} without disturbing the scene",
            "I ask the right question in {place} and {who} answer too much",
            "I piece together {clue} and {evidence} into one clear answer",
        ],
        'Failure': [
            "I search {place} thoroughly and find nothing useful",
            "I miss {clue} in {where} that was right in front of me",
            "I follow a false lead from {evidence} and waste time",
            "I contaminate the scene in {place} and ruin what was left",
            "I draw the wrong conclusion from {clue} and steer us wrong",
            "I overlook {hidden} that {who} catch later",
            "I can't make {evidence} fit any theory that works",
            "I get distracted in {where} and lose the thread",
        ],
    },
    'Medicine': {
        'Success': [
            "I diagnose {symptom} in {patient} in {place} and know the treatment",
            "I stabilize {injury} near {who} before it worsens",
            "I recognize poison in {symptom} and act fast",
            "I clean and bind {injury} with what we have on hand",
            "I keep {patient} conscious in {where} until proper help arrives",
            "I spot infection early in {injury} and stop it spreading",
            "I set the bone, stitch the cut, or brew the draught that works",
            "I talk {patient} through shock in {place} until color returns",
        ],
        'Failure': [
            "I misdiagnose {symptom} in {patient} in {place} and treat the wrong thing",
            "I fumble the bandage on {injury} and cause more pain",
            "I can't tell poison from exhaustion in {symptom}",
            "My hands shake in {where} and {patient} worsens",
            "I apply the wrong remedy to {injury} and regret it",
            "I miss the internal damage to {patient} until it's obvious",
            "I try to help {patient} and make the bleeding worse",
            "I lack supplies in {place} and can't do enough for {injury}",
        ],
    },
    'Nature': {
        'Success': [
            "I identify {flora} in {place} instantly and know if it's safe",
            "I read {fauna} sign in {terrain_nat} and know what's nearby",
            "I recognize {weather} building over {place} before it hits",
            "I explain {flora} to {who} before anyone eats the wrong thing",
            "I predict danger from {fauna} in {where} and reroute us",
            "I know which path through {terrain_nat} won't collapse or flood",
            "I spot the venomous look-alike among {flora} and warn the party",
            "I hear {fauna} go quiet in {place} and know predators are close",
        ],
        'Failure': [
            "I misidentify {flora} in {place} and nearly poison us",
            "I read {fauna} sign wrong in {terrain_nat} and choose a bad route",
            "I dismiss {weather} signs in {where} and we pay for it",
            "I touch the wrong {flora} and itch for hours",
            "I underestimate {fauna} near {place}",
            "I confuse edible and toxic {flora} in {where}",
            "I ignore {whose} warnings and trust bad nature lore",
            "Nature outsmarts my knowledge in {place} today",
        ],
    },
    'Perception': {
        'Success': [
            "I spot {hidden_thing} in {place} before anyone else",
            "I hear {noise} in {where} that doesn't belong",
            "I catch movement in {shadow} near {who}",
            "I notice the trap, peephole, or pickpocket in {place}",
            "I see what's wrong with {evidence} while {who} chat",
            "I smell {scent} in {where} first and raise the alarm",
            "I find {clue} near {hidden} before it's gone",
            "I watch {mark} in {place} and catch the tell",
        ],
        'Failure': [
            "I walk past {hidden_thing} in {place} without seeing it",
            "I miss the ambush setup in {where} until it's almost too late",
            "I don't hear {noise} approaching in {place}",
            "I stare at {evidence} and still overlook {hidden}",
            "I'm distracted in {place} and {who} notice first",
            "I fail to spot {mark} watching us from {shadow}",
            "I miss {scent} that should've warned us in {where}",
            "I scan {place} and report all clear — incorrectly",
        ],
    },
    'Performance': {
        'Success': [
            "I command {audience} in {place} from the first note or word",
            "I turn {where} into {stage} and own it for one set",
            "I deliver {act} near {stage} like it was built for me",
            "I recover a flub in {where} so smoothly it looks intentional",
            "I finish strong in {place} and {audience} erupt",
            "I match the mood of {place} and elevate it",
            "I win laughs, tears, or silence from {audience} exactly when I mean to",
            "I leave {where} buzzing about {act}",
        ],
        'Failure': [
            "My {act} in {place} dies before the second verse",
            "I forget my lines on {stage} and stall badly",
            "I misread {audience} in {where} and bomb",
            "I trip over {obstacle} mid-act and never recover",
            "I play to {audience} who clearly aren't interested",
            "My voice cracks in {place} at the worst moment",
            "I attempt grandeur on {stage} and get pity applause",
            "The room in {where} stays painfully quiet",
        ],
    },
    'Persuasion': {
        'Success': [
            "I find the exact argument that moves {negotiator} in {place}",
            "I appeal with {pitch} in {where} and win",
            "I talk {negotiator} into the sensible choice without threats",
            "I negotiate with {offer} near {who} and both sides feel heard",
            "I reframe the situation so {negotiator} sees our side",
            "I keep my tone warm in {place} and get agreement",
            "I persuade {negotiator} to help us when others failed",
            "I turn resistance in {where} into reluctant cooperation",
        ],
        'Failure': [
            "My pitch to {negotiator} in {place} lands flat",
            "I push too hard in {where} and close the door entirely",
            "I misjudge what {negotiator} cares about",
            "I argue with {who} instead of persuading them",
            "I sound desperate in {place} and lose leverage",
            "I fail to read the room in {where} and step on toes",
            "I make promises to {negotiator} nobody believes",
            "I convince nobody in {place} despite my best speech",
        ],
    },
    'Religion': {
        'Success': [
            "I recall {doctrine} that applies in {place}",
            "I recognize the rite tied to {shrine} and perform it correctly",
            "I explain the omen at {shrine} using sacred texts",
            "I identify the deity's symbol in {place} and its meaning",
            "I calm {who} with the right prayer at {shrine}",
            "I know which taboo we're near in {place} and avoid offense",
            "I interpret {inscription} on {shrine} accurately",
            "I cite {doctrine} in {where} and {negotiator} listens",
        ],
        'Failure': [
            "I misquote {doctrine} in {place} and get corrected harshly",
            "I confuse two faiths in {where} and offend {who}",
            "I can't remember the rite for {shrine}",
            "I misread the omen at {shrine} completely",
            "I guess at {doctrine} in {place} and guess wrong",
            "I treat {shrine} casually and regret it",
            "I fail to recognize the symbol on {relic}",
            "I draw blank on scripture when {negotiator} asks",
        ],
    },
    'Sleight of Hand': {
        'Success': [
            "My hands move faster than {who} can follow in {place}",
            "I palm {item} near {mark} without a flicker of suspicion",
            "I swap {item} for the decoy in {where} cleanly",
            "I lift from {mark} while they watch {distraction}",
            "I tie, untie, or pick {hidden} in {where} before anyone notices",
            "I plant {evidence} on {mark} in {place} smoothly",
            "I cheat at cards while {audience} watch the wrong hand",
            "I conceal {item} in {pocket} until the perfect moment",
        ],
        'Failure': [
            "I drop {item} in {place} and everyone sees",
            "I fumble near {mark} and get caught cold",
            "My swap in {where} is clumsy and obvious",
            "I snag my sleeve mid-trick in {place}",
            "I move too slow near {mark} and get called out",
            "I misjudge {whose} attention and reveal both hands",
            "I try to lift from {mark} and they feel everything",
            "My sleight in {place} becomes a public embarrassment",
        ],
    },
    'Stealth': {
        'Success': [
            "I move through {place} without adding to {noise}",
            "I use {shadow} and {cover_stealth} to stay unseen",
            "I pass behind {guard} in {where} and nobody turns",
            "I reach {hidden} and back away unnoticed",
            "I hold still in {cover_stealth} until {guard} moves on",
            "I slip past {guard} in {where} on silent feet",
            "I blend into {shadow} until I become part of the background",
            "I cross {place} leaving no sign I was there",
        ],
        'Failure': [
            "I kick {item} in {place} and the noise gives me away",
            "I step into {light} in {where} like a spotlight found me",
            "I stumble on {obstacle} and {guard} turn instantly",
            "My gear clinks in {where} and ruins everything",
            "I try to hide in {cover_stealth} and {guard} point right at me",
            "I misjudge {shadow} and stand out worse",
            "I sneeze or curse in {place} at the worst time",
            "I thought I was hidden in {shadow} — I wasn't",
        ],
    },
    'Survival': {
        'Success': [
            "I read {trail} in {terrain_nat} and choose the safe path",
            "I find {shelter} in {place} before the elements turn lethal",
            "I start a fire in {where} with stubborn materials",
            "I locate {forage} or water when supplies run low",
            "I rig {shelter} from what {place} offers and keep {who} alive",
            "I predict {weather} in {where} and avoid it early",
            "I navigate {terrain_nat} without getting turned around",
            "I preserve supplies in {place} when options are thin",
        ],
        'Failure': [
            "I misread {trail} in {terrain_nat} and lead us astray",
            "I can't get a fire going in {place} despite trying",
            "I choose the wrong camp in {where} and pay for it",
            "I waste hours in {terrain_nat} chasing a false {trail}",
            "I eat the wrong {forage} and feel it later",
            "I ignore {weather} signs in {place} until we're in trouble",
            "I lose the path in {where} and panic sets in",
            "The conditions in {place} beat my survival instincts today",
        ],
    },
}

# Skill-accurate generic fallbacks (no scene words like "trail" or "gossip").
GENERIC_SKILL_LINES = {
    'Acrobatics': {
        'Success': [
            "I gracefully flip over the obstacle, landing perfectly on my feet",
            "My body moves like liquid, flowing through the narrow space with ease",
            "I execute a perfect cartwheel, my feet barely touching the ground",
            "With a fluid motion, I balance on the narrow beam as if I were born to it",
            "I stick the landing when everyone expected me to fall",
            "I roll out of a bad fall and come up running",
            "I use momentum instead of fighting it and stay on my feet",
            "I make a dangerous leap look effortless",
        ],
        'Failure': [
            "I attempt a flip but land flat on my back with a loud thud",
            "My foot slips and I tumble awkwardly to the ground",
            "I misjudge the distance and crash into the obstacle instead of over it",
            "My balance fails me completely, and I fall in an undignified heap",
            "I try to look graceful and faceplant instead",
            "My landing sends me skidding into something I did not mean to hit",
            "I overestimate my footing and sprawl at the worst moment",
            "I attempt flair and end up tangled in my own gear",
        ],
    },
    'Animal Handling': {
        'Success': [
            "The creature calms under my gentle touch, recognizing a friend",
            "I speak softly to the animal, and it responds with trust",
            "My understanding of animals shines through as the beast relaxes",
            "The creature recognizes my calm demeanor and approaches willingly",
            "I read its ears, tail, and breath and respond before it spooks",
            "I offer food with steady hands and patience until it takes it",
            "I guide the animal away from danger without force or shouting",
            "I keep my movements small until fear turns into trust",
        ],
        'Failure': [
            "The creature sees me as a threat and backs away, baring its teeth",
            "My approach startles the animal, causing it to flee",
            "I misread the creature's signals and make it more agitated",
            "The beast doesn't trust me and shows clear signs of aggression",
            "I reach too fast and get snapped at for my trouble",
            "I speak too loud and every animal nearby panics",
            "I grab at the wrong moment and lose its trust entirely",
            "I thought I understood the beast — I didn't",
        ],
    },
    'Arcana': {
        'Success': [
            "I recognize the magical pattern immediately, understanding its purpose",
            "My knowledge of arcane theory helps me decipher the enchantment",
            "The magical energy reveals its secrets to my trained eye",
            "I identify the spell components and their interactions perfectly",
            "I sense unstable magic and know how to avoid triggering it",
            "I name the school of magic involved without guessing",
            "I decode the sigils and piece together the caster's intent",
            "I explain the ward clearly enough that nobody pokes it",
        ],
        'Failure': [
            "The magical symbols look like gibberish to my untrained eye",
            "I can't make sense of the arcane patterns, despite my best efforts",
            "The magical energy confuses me, its purpose unclear",
            "My knowledge fails me, and the enchantment remains a mystery",
            "I misidentify the magic and almost make things worse",
            "I touch something warded thinking it's harmless",
            "I confuse two schools of magic and give bad advice",
            "Whatever magic lingers here refuses to make sense to me",
        ],
    },
}

# Fill remaining skills with copies from templates using neutral wilderness nouns
_neutral = {**TYPE_NOUNS['wilderness'], 'place': 'the area', 'where': 'here', 'who': 'the party'}
_neutral['whose'] = "the party's"
for _skill, _templates in SKILL_TEMPLATES.items():
    if _skill in GENERIC_SKILL_LINES:
        continue
    GENERIC_SKILL_LINES[_skill] = {}
    for _suffix in ('Success', 'Failure'):
        _key = 'Success' if _suffix == 'Success' else 'Failure'
        _lines = []
        for _t in _templates[_key]:
            _line = _t.format(**_neutral)
            if _line not in _lines:
                _lines.append(_line)
            if len(_lines) >= 16:
                break
        GENERIC_SKILL_LINES[_skill][_suffix] = _lines


def possessive(noun):
    """Grammatically correct possessive: plural 'soldiers' -> "soldiers'"."""
    noun = noun.strip()
    if noun.endswith('s'):
        return noun + "'"
    return noun + "'s"


def vocab_for(scene_id):
    stype = SCENE_TYPE[scene_id]
    nouns = dict(TYPE_NOUNS[stype])
    nouns.update(SCENE_NOUN_OVERRIDES.get(scene_id, {}))
    if scene_id in SCENE_CONTEXT:
        nouns['place'] = SCENE_CONTEXT[scene_id].get('place', nouns['place'])
        nouns['who'] = SCENE_CONTEXT[scene_id].get('who', nouns['who'])
    nouns['where'] = nouns.get('where', 'here')
    nouns['scene'] = scene_id
    stype = SCENE_TYPE[scene_id]
    nouns.setdefault('light', TYPE_NOUNS[stype]['light'])
    nouns['whose'] = possessive(nouns['who'])
    return nouns

# Per-skill banned substrings — reject cross-skill bleed
SKILL_BANNED = {
    'Animal Handling': ['gossip', 'arcane pattern', 'persuade', 'negotiate', 'doctrine', 'sigil', 'spell components', 'barroom noise', 'local gossip', 'awkward silence', 'murder hole', 'arrow slits'],
    'Arcana': ['gossip', 'barroom noise', 'local gossip', 'animal calms', 'beast', 'pack mule', 'tavern cat'],
    'Athletics': ['gossip', 'arcane', 'doctrine', 'sigil'],
    'History': ['beast calms', 'pack mule', 'palming'],
    'Medicine': ['gossip', 'arcane pattern', 'sigil', 'negotiate'],
    'Nature': ['gossip', 'barroom', 'doctrine', 'sigil on the bar'],
    'Religion': ['pack mule', 'palming', 'card cheat'],
    'Performance': ['pack mule', 'pressure plate', 'quicksand'],
    'Persuasion': ['beast calms', 'giant rat', 'sigil on the floor'],
    'Sleight of Hand': ['doctrine', 'prayer', 'beast calms'],
    'Stealth': ['doctrine', 'beast calms', 'negotiate'],
    'Survival': ['barroom', 'gossip', 'sigil on the bar'],
    'Investigation': ['beast calms', 'doctrine'],
    'Insight': ['beast calms', 'sigil'],
    'Intimidation': ['beast calms', 'doctrine'],
    'Perception': ['doctrine', 'negotiate'],
    'Deception': ['beast calms', 'doctrine'],
    'Acrobatics': ['beast calms', 'gossip', 'doctrine'],
}


def line_is_valid(skill, line):
    lower = line.lower()
    for bad in SKILL_BANNED.get(skill, []):
        if bad.lower() in lower:
            return False
    if skill == 'Animal Handling':
        absurd = ['gelatinous', 'cube', 'colony', 'flock', 'nest of', 'everyone knows by name\'s ears']
        if any(x in lower for x in absurd):
            return False
    return True
