"""
Scene-specific situation beats and skill combo templates.
Generates lines that read like distinct events, not the same sentence with {place} swapped.
"""

# Concrete situation beats per scene — no {place} required in the beat itself.
SCENE_BEATS = {
    'Village': [
        'the well rope fraying at the knot',
        'fresh wagon ruts that turn off the main road',
        'a child repeating a rumor too loudly',
        'smoke from the wrong chimney at this hour',
        'a dog that will not stop staring at the hedgerow',
        'chalk marks on the barn door',
        'a villager counting coins twice before paying',
        'the bell at the shrine ringing once, then stopping',
        'bootprints that do not match anyone in the square',
        'a shutter slamming shut when we look up',
        'the smell of iron where there is no smithy nearby',
        'someone pretending to mend a fence while watching us',
    ],
    'Town Square': [
        'the notice board with a fresh paper pinned over an old one',
        'a guard changing patrol route mid-round',
        'two merchants arguing over the same corner stall',
        'pigeons scattering from the fountain rim all at once',
        'a crowd parting around someone they will not look at',
        'a dropped proclamation trampled but not read',
        'the town crier rehearsing under his breath',
        'a ladder leaning against the wrong building',
        'coin changing hands under a handkerchief',
        'a child pointing at us then being shushed hard',
        'the flag on the hall hanging lower on one side',
        'footsteps keeping pace with us across the cobbles',
    ],
    'Tavern': [
        'the card game where nobody wins but nobody leaves',
        'a tankard sliding toward the edge of the bar',
        'the stranger nursing one drink for an hour',
        'a wanted poster half-peeled from the wall',
        'the musician tuning the same string three times',
        'a brawl that has not started but everyone is ready',
        'chalk tallies behind the bar that do not add up',
        'someone palming dice under the table lip',
        'the back-room door that opens only a crack',
        'a regular who stops mid-sentence when we enter',
        'the hearth poker moved to the wrong hook',
        'boots on the stairs that pause when the room goes quiet',
    ],
    'Inn': [
        'a floorboard that creaks in the wrong rhythm',
        'luggage stacked outside the wrong room',
        'a window latch that is locked from outside',
        'whispering in the hall that stops at our door',
        'a candle burned down in an empty room',
        'the guest book with yesterday\'s page torn out',
        'a key hanging on the wrong peg behind the desk',
        'mud on the carpet that nobody has explained',
        'a meal tray left outside a bolted door',
        'the stable boy refusing to look at the upper floor',
        'a rope tied to the bed frame for no good reason',
        'footsteps above us when the inn should be empty',
    ],
    'Market': [
        'a vendor closing up despite the midday crowd',
        'spices piled in a pattern that hides something underneath',
        'a purse changing hands too quickly to count',
        'a donkey braying at an empty stall',
        'the same phrase shouted by two rival hawkers',
        'a bolt of cloth with a stain that is not dye',
        'a child running with something too large to steal',
        'scales that do not balance until the vendor touches them',
        'a guard watching one stall and nothing else',
        'a crate marked fragile that sounds like metal inside',
        'the smell of rot from a stall selling fresh fruit',
        'a merchant reading lips across the aisle',
    ],
    'Shop': [
        'a trinket displayed twice in different prices',
        'the shop cat staring at a blank wall',
        'a ledger left open to a name someone tried to scratch out',
        'dust on the counter except where two fingers rested',
        'a bell above the door that does not ring when it should',
        'merchandise arranged to block the back curtain',
        'a lockbox with scratches around the keyhole',
        'the shopkeeper quoting a price before we ask',
        'a mirror angled to watch the street without turning',
        'string tied between shelves at ankle height',
        'a smell of oil from a shop that sells cloth',
        'a drawer that will not quite shut all the way',
    ],
    'Temple': [
        'incense burning in a side chapel nobody is using',
        'a candle lit for a name not on the memorial wall',
        'a clergy member skipping every second step on the stairs',
        'holy water that ripples without a draft',
        'a donation box with fresh scratches inside the slot',
        'prayer beads left on the wrong altar',
        'a hymn ending one verse early when we enter',
        'a symbol drawn in ash on the threshold',
        'whispers from the confession alcove with no priest inside',
        'a relic case that has been opened recently',
        'a novice staring at us instead of the scripture',
        'footprints on the clean floor leading to a locked door',
    ],
    'Blacksmith': [
        'a horseshoe nailed up upside down',
        'coal piled as if someone left in a hurry',
        'a blade quenched the wrong color for the steel',
        'the forge banked but the bellows still warm',
        'hammer marks on the anvil in a pattern not from work today',
        'a customer\'s order hanging with no name tag',
        'the smith\'s apprentice watching the street not the fire',
        'water in the trough that should be steaming but is not',
        'a chain coiled like it was dropped mid-task',
        'sparks that fly when no one is striking metal',
        'a shield dent that matches no weapon in the shop',
        'the smell of blood under the hot iron scent',
    ],
    'Listening for Rumors': [
        'a story that changes details each time it is retold',
        'two locals who stop talking when we sit within ten feet',
        'a name whispered once then replaced with another',
        'a drink bought for us by someone who will not join the table',
        'the same rumor arriving from opposite ends of the room',
        'a map drawn on a napkin then swallowed',
        'laughter at a joke nobody will repeat for us',
        'a patron who only speaks in questions',
        'a song with one verse everyone skips',
        'a warning disguised as a toast',
        'eyes flicking to the door whenever a title is mentioned',
        'a tale that ends mid-sentence when the teller sees our gear',
    ],
    'Castle': [
        'a tapestry that bulges where the wall should be flat',
        'servants carrying trays to the wrong wing',
        'a guard saluting the wrong rank',
        'a feast being prepared for guests who are not on the list',
        'a herald practicing a name they keep mispronouncing',
        'armor displayed with fresh strap cuts',
        'a courtier\'s smile that never reaches their eyes',
        'a door guarded by two men who will not look at each other',
        'a raven on the battlement watching the courtyard',
        'a banquet hall set for twice the expected number',
        'a shield turned backward on the wall of honors',
        'footsteps echoing one beat behind ours in the hall',
    ],
    'Dungeon': [
        'a hair-thin wire stretched at ankle height',
        'fresh scuff marks where stone should not move',
        'torchlight that flickers without a draft',
        'a peephole plug sitting one inch out of true',
        'chalk arrows pointing two different directions',
        'a door that is warm on the iron side',
        'dripping water counting an interval that changes',
        'a pit edge disguised with dust too evenly spread',
        'breathing from behind what looks like solid wall',
        'a glyph scratched out but still faintly glowing',
        'bootprints that stop abruptly at a blank wall',
        'a chain hanging that still swings slightly',
    ],
    'Ruins': [
        'a column holding weight it should not survive',
        'carvings defaced in a pattern not random vandalism',
        'a bird nest built in a room with no roof',
        'rubble stacked to hide a crawl space',
        'a stair that ends in mid-air with fresh mud on it',
        'an inscription partially chiseled away recently',
        'a breeze from below with no visible opening',
        'flowers growing only on one side of the courtyard',
        'a campfire site cold but the ashes are stirred',
        'a statue turned to face the wrong door',
        'echoes that answer our steps one beat late',
        'a rope anchor driven into stone that is not climbing gear',
    ],
    'Cave': [
        'stalactite tips that are wet when the ceiling is dry elsewhere',
        'a bat colony silent for no reason we can see',
        'waterline marks higher than the current pool',
        'a narrow crack with air moving through it',
        'mineral streaks that form an arrow if you stand here',
        'a bone pile sorted too neatly to be natural',
        'our voices returning from the wrong direction',
        'a glow without a visible source around the bend',
        'footprints in mud that end at a pool\'s edge',
        'a rope cut clean with no fraying',
        'a cache of supplies hidden under a flat stone',
        'claw marks that stop as if something was lifted away',
    ],
    'Crypt': [
        'a sarcophagus lid shifted by a finger\'s width',
        'candles burned down in a tomb sealed for centuries',
        'a name on the wall that matches someone in our party\'s accent',
        'incense ash in a room with no censer',
        'a burial shroud folded as if someone stood up',
        'holy symbols turned face-down on purpose',
        'a coffin nail bent outward not inward',
        'footprints in dust that lead in but not out',
        'a whisper that is only the wind except it is not windy',
        'a ring of salt broken on one side',
        'a mural figure with eyes that follow the torch',
        'a lock that was picked recently despite the seal',
    ],
    'Tower': [
        'a spiral stair with steps worn on the wrong edge',
        'arrow slits that frame the courtyard too perfectly',
        'a bell rope cut halfway up',
        'murder holes with fresh scratch marks below them',
        'a landing door barred from our side unexpectedly',
        'a rookery empty but feathers still warm',
        'a map pinned with daggers through the wrong towns',
        'wind that howls only on one floor',
        'a chain hoist holding weight it should not',
        'graffiti in a language nobody admits to reading',
        'a window shutter banging with no latch broken',
        'footsteps on the roof when we are at the top already',
    ],
    'Fort': [
        'a palisade gate that opens without the usual challenge',
        'soldiers drilling a formation they keep breaking on purpose',
        'a supply cart missing the seal but not the cargo',
        'a banner flying the wrong color for this season',
        'a watchtower fire lit in daylight',
        'boots lined up by size except one pair missing',
        'a message tube empty but the wax is fresh',
        'a weapon rack with gaps in a pattern not from use',
        'a sergeant counting heads twice in one minute',
        'mud on the parade ground in a single track line',
        'a dog that growls only at officers',
        'a horn call answered from the wrong wall',
    ],
    'Sewers': [
        'a grate above us with voices that stop when we pause',
        'a current in the runoff going the wrong direction today',
        'a rat colony parting like something bigger is behind them',
        'a ladder rung replaced with rope recently',
        'a chalk mark at an intersection we already passed',
        'a smell of perfume where sewage should be',
        'a brick that sounds hollow when the water drips on it',
        'a torch sconce with fresh oil in an abandoned stretch',
        'a boot stuck in the muck that is not ours',
        'echoes that mimic our words one syllable off',
        'a pipe dripping faster when we approach',
        'a nest of bottles arranged like a signal',
    ],
    'Mine': [
        'a timber brace cracked but still holding',
        'cart rails polished by use where maps say this branch is closed',
        'a canary cage swinging though nobody touched it',
        'ore sacks stacked to hide a side tunnel',
        'a pickaxe buried blade-first in the wall',
        'a foreman\'s tally board with today\'s shift crossed out twice',
        'a lantern left burning in a section marked unsafe',
        'a rope that vibrates like someone is pulling the far end',
        'a vein of ore chipped at in the last hour',
        'bootprints in coal dust leading toward a collapse',
        'a whistle echo with no miner answering roll call',
        'a tool belt hanging on a support that should not bear weight',
    ],
    'Forest': [
        'a game trail that forks where maps show one path',
        'broken branches at chest height in a straight line',
        'a bird alarm call that stops when we freeze',
        'moss scraped off trees in a direction we are not going',
        'a campfire ring with ash still warm',
        'claw marks on bark higher than any local beast should reach',
        'a stream running muddy upstream with no rain today',
        'a cairn stacked with stones not from this valley',
        'spores in the air that make the torch flame turn green',
        'a snare made with rope not vine',
        'feathers from a bird that should not be this deep in the wood',
        'silence where insects should be loud',
    ],
    'Mountains': [
        'a goat path that ends at a cliff with fresh chalk marks',
        'snow melt on a slope that should be in shadow all day',
        'a cairn with a stone removed from the bottom not the top',
        'wind that shifts direction every dozen steps',
        'a rope anchor hammered into rock that is not climbing rock',
        'eagle cries answering each other in a pattern like signals',
        'a cave mouth blocked with branches cut today',
        'ice on a rock face that melted in one stripe only',
        'a boot nailed to a post as a warning',
        'clouds stacking on the peak we are not heading toward',
        'a landslide scrape with tools still stuck in it',
        'our echo returning with an extra footstep',
    ],
    'Hills': [
        'sheep trails that circle the same hill three times',
        'a standing stone turned slightly since the last map',
        'smoke from a hollow with no chimney visible',
        'a hawk circling one patch of ground repeatedly',
        'furrows in the grass like something heavy was dragged uphill',
        'a well cover off its hinges though the village is miles away',
        'wildflowers trampled in a line over the ridge',
        'a fence mended with wire not local to this region',
        'a bell on a sheep that rings only when we move',
        'mud on the high path when the valley is dry',
        'a campfire smell with no visible fire',
        'a path marker knocked down facing the wrong valley',
    ],
    'Desert': [
        'a dune with ripples on the wrong side for this wind',
        'a skeleton with gear stripped but not scavenged by beasts',
        'a mirage that holds steady longer than it should',
        'tracks that start abruptly with no approach trail',
        'a cactus scored with marks like a calendar',
        'a cloth strip tied to a dead bush flapping a pattern',
        'heat shimmer that blocks sight of the oasis we were heading to',
        'a snake trail crossing ours and doubling back',
        'a buried pot handle sticking up at a fresh angle',
        'stars visible before sunset on this horizon only',
        'a well lid sanded over too recently to be abandoned',
        'a buzzard circling something we cannot see yet',
    ],
    'Jungle': [
        'vines cut with a blade not teeth or weather',
        'a parrot repeating a word in Common once then going silent',
        'a footprint in mud that fills with water too fast',
        'fruit picked from the wrong side of the clearing',
        'a monkey screaming at something behind us not ahead',
        'a rope bridge with one strand freshly frayed',
        'flowers blooming on only the trees facing the river',
        'a stone idol knocked over but not stolen',
        'insects going quiet ten paces before the clearing',
        'a hunter\'s blind built facing the trail we came from',
        'a snake skin shed in a circle not a line',
        'steam rising from ground that should not be hot',
    ],
    'Plains': [
        'a hawk dive at something hidden in the grass',
        'wagon ruts crossing ours at a fight angle',
        'a windmill turning with no wind at ground level',
        'cattle clustered away from one patch of open ground',
        'a rider on the horizon who vanishes when we wave',
        'a scarecrow facing the road instead of the field',
        'a fire pit with bones sorted not burned together',
        'cloud shadows that move slower than the clouds',
        'a milestone knocked over pointing backward',
        'wildflowers crushed in a circle the size of a tent',
        'a kite tangled in fence wire still twitching',
        'dust rising from a hollow with no herd visible',
    ],
    'Swamp / Marsh': [
        'bubbles in the mud that stop when we speak',
        'a will-o-wisp that keeps pace but never closes',
        'a boardwalk plank replaced with one too short',
        'a bird that takes off without calling first',
        'a tree with bark stripped in hand-width strips',
        'a pole in the water with fresh knot work',
        'a smell of rot stronger on the safe-looking path',
        'fireflies clustering over one patch of open water',
        'a boat tied to a root that was cut recently',
        'insects loud on one side of us silent on the other',
        'a frog chorus that cuts off one note early',
        'a trail marker sunk to its tip since yesterday',
    ],
    'Coast': [
        'tide pools drained in a pattern not natural',
        'a net mended with knotwork from inland not sailors',
        'gulls screaming at a spot on the water with no fish',
        'a boat pulled up with barnacles still wet on the hull',
        'a message in a bottle wedged where high tide cannot reach yet',
        'a dock plank loose only where footsteps would land',
        'salt crust on rocks in the shape of a handprint',
        'a fish kill washed up in a line not a scatter',
        'a lighthouse dark on a night with no cloud cover',
        'a shell pile sorted by size not species',
        'a rope coil hung as if ready to cast off with no crew',
        'footprints in wet sand ending at the water with none returning',
    ],
    'Tundra': [
        'a snow berm with a tunnel mouth too round to be wind-carved',
        'aurora light reflecting off something metal under the drifts',
        'a sled track that turns back without a camp site',
        'breath fog that hangs longer than the cold explains',
        'a cairn topped with a glove still warm inside',
        'cracks in the ice forming a star around one point',
        'a wolf howl answered from two directions at once',
        'a fire pit dug in snow with no ash in the bottom',
        'a fur cloak snagged on brush that should be buried in ice',
        'wind that stops entirely for one heartbeat then roars',
        'a pole driven into ice with fresh hammer marks',
        'our shadows stretching toward a sun that should be behind us',
    ],
    'Bad Weather': [
        'lightning striking the same hill twice in one minute',
        'hail that hits only one side of the camp',
        'a gust that smells of chimney smoke with no hearth nearby',
        'rain falling hard in a column the width of a tent',
        'a tree split by lightning with the inner wood still dry',
        'a river rising faster upstream than where we stand',
        'a tarp peg pulled loose though the knot is still tight',
        'thunder that rolls without a visible cloud above us',
        'a path turned to mud except one strip of dry ground',
        'a bird flying low against the wind then suddenly still',
        'a puddle rippling before the rain reaches it',
        'a shelter rope humming a note that changes when we move',
    ],
    'Travelling / On the Trail': [
        'a milestone scratched with a date from tomorrow',
        'a campfire site with ashes still arranged in a cooking ring',
        'a horseshoe nailed to a tree as a trail sign reversed',
        'tracks that overlap ours without passing us',
        'a waterskin hanging on a branch nobody claims',
        'a fork in the path with a broken sign pointing both ways',
        'a bird following us from treeline to treeline',
        'a scrap of map wedged under a rock with fresh ink',
        'a bell on a mule that rings out of rhythm with its steps',
        'a patch of trampled grass where someone waited a long time',
        'a smell of smoke with no column visible',
        'a bootlace tied to a bush in a hunter\'s knot',
    ],
    'Camp': [
        'a bedroll footprint that does not match anyone awake',
        'the cook pot scraped clean before second watch',
        'a horse tied facing away from the fire for no reason',
        'a watch log with one hour blank in the middle',
        'a tent flap tied from outside while we are inside',
        'a dagger stuck in a tree with a string on the hilt',
        'the fire burning green for one breath then normal',
        'a supply bag lighter than it was at sunset',
        'a snare set fifty feet from camp nobody admits to',
        'a cloud of moths circling one bedroll only',
        'a boot print at the latrine that is the wrong size',
        'a whispered argument that stops when the fire pops',
    ],
    'Carnival / Feywild (Wild Beyond The Witchlight)': [
        'a ticket stub that shows a time that has not happened yet',
        'a game booth where the prizes are watching us back',
        'confetti falling indoors with no hole in the ceiling',
        'a strongman bell rung with no one on the platform',
        'a mirror maze reflection that waves one beat late',
        'a calliope playing a tune we only half remember from childhood',
        'a rigged dartboard with every dart in the bullseye already',
        'a clown makeup stain on a pillar nobody dressed as a clown passed',
        'a tent interior bigger than the tent exterior from outside',
        'a ticket taker who stamps our hands with the wrong color',
        'a carousel horse turned to face the crowd not the ride',
        'a lost thing sign describing something one of us is wearing',
    ],
}

# Skill-specific templates using {beat} — structurally different from skill_templates_v2.
SKILL_BEAT_TEMPLATES = {
    # Physical/treatment skills treat the beat as an AMBIENT distraction or backdrop,
    # never as the thing physically acted upon — a beat is an observation/clue, so
    # "haul past {beat}" or "misdiagnose what {beat} caused" reads as nonsense.
    'Acrobatics': {
        'Success': [
            'I tumble through the space clean while every eye stays on {beat}',
            'I turn a near-slip into a spin and pretend it upstaged {beat}',
            'I vault the gap and land grinning, using {beat} as my distraction',
            'I weave through on light feet before anyone looks away from {beat}',
            'I stick the landing and bow, daring {beat} to be more interesting',
        ],
        'Failure': [
            'I try to show off near {beat} and eat the ground in front of everyone',
            'I misjudge the leap, distracted by {beat}, and land in a graceless heap',
            'My foot catches mid-flourish and the tumble outshines {beat}',
            'I crash loud enough that even {beat} loses the room to me—wrong way to win it',
        ],
    },
    'Animal Handling': {
        'Success': [
            'I calm the animal while {beat} keeps the humans occupied',
            'I read its mood and ease it down, using {beat} to mask my approach',
            'I keep it from bolting even as {beat} sets everyone else on edge',
            'I coax cooperation with slow hands, ignoring {beat} entirely',
        ],
        'Failure': [
            'I move too fast, distracted by {beat}, and the animal panics exactly as predicted',
            'I misread the warning signs while watching {beat} and nearly lose a finger',
            'My approach spooks every beast nearby, and {beat} only makes the noise worse',
        ],
    },
    'Arcana': {
        'Success': [
            'I sense the wrongness around {beat} and name the magic before anyone touches it',
            'I trace the enchantment tied to {beat} and explain what not to do',
            'I recognize the ward on {beat} and how to avoid triggering it',
            'I decode the magical residue by {beat} like reading a bad chorus structure',
        ],
        'Failure': [
            'I misidentify the magic on {beat} and almost get us cursed for confidence',
            'The aura by {beat} makes no sense to me today and I bluff anyway',
            'I touch something near {beat} I should have left alone',
        ],
    },
    'Athletics': {
        'Success': [
            'I power through the obstacle while every other eye stays glued to {beat}',
            'I muscle past the hard part, using the fuss over {beat} to cover my grunting',
            'I haul us clear before anyone looks up from {beat}',
            'I shoulder through the crush and leave {beat} for someone with less to lift',
            'I make the climb look easy, narrating it louder than {beat} deserves',
        ],
        'Failure': [
            'I strain and fail loudly enough that even {beat} can not cover the noise',
            'I lose my grip at the worst moment, right as {beat} stops holding the room',
            'I overcommit, stumble, and add my own clatter to the fuss over {beat}',
            'I gas out halfway and need a hand while {beat} steals my only witnesses',
        ],
    },
    'Deception': {
        'Success': [
            'I sell a cover story about {beat} that holds under one round of questions',
            'I misdirect attention from {beat} before anyone connects the dots',
            'I play innocent about {beat} with a straight face and bardic timing',
            'I redirect the conversation away from {beat} like a good hook change',
        ],
        'Failure': [
            'My story about {beat} collapses the moment someone asks a follow-up',
            'I stammer at the mention of {beat} and my wings give me away',
            'I contradict myself about {beat} in front of the wrong audience',
        ],
    },
    'History': {
        'Success': [
            'I recognize {beat} as a clue from an old story and explain why it matters',
            'I connect {beat} to {era} before {who} repeat the same mistake',
            'I recall the legend tied to {beat} and warn the party in time',
            'I translate the implication of {beat} without guessing',
        ],
        'Failure': [
            'I swear {beat} means something famous and get corrected immediately',
            'I misdate what {beat} implies by centuries in front of {who}',
            'I invent a history for {beat} that falls apart under one question',
        ],
    },
    'Insight': {
        'Success': [
            'I notice how {who} react to {beat} and know who is lying',
            'I catch the tell at the mention of {beat} and adjust my approach',
            'I read the room around {beat} and see who is holding back',
            'I sense fear not anger behind the reaction to {beat}',
        ],
        'Failure': [
            'I trust the wrong person about {beat} and miss the setup',
            'I misread the reaction to {beat} and advise the party badly',
            'I assume honesty about {beat} until the punchline lands on us',
        ],
    },
    'Intimidation': {
        'Success': [
            'I make my threat feel real without raising a hand, {beat} sharpening the quiet',
            'I stare them down until they reconsider, {beat} forgotten behind me',
            'I turn the mood cold and let {beat} do half the menacing for me',
            'I let the silence stretch while {beat} keeps everyone on edge',
        ],
        'Failure': [
            'I try to menace the room and they laugh, more interested in {beat} than my sparkle',
            'My intimidation lands like a lullaby while {beat} steals the tension',
            'I bark orders and {who} ignore me, {beat} apparently scarier than I am',
        ],
    },
    'Investigation': {
        'Success': [
            'I connect {beat} to {hidden} and the picture finally clears',
            'I find the detail in {beat} everyone else walked past',
            'I reconstruct what happened at {beat} from timing and scraps',
            'I follow the thread from {beat} without contaminating the scene',
        ],
        'Failure': [
            'I search around {beat} thoroughly and find nothing useful',
            'I miss the obvious clue in {beat} until someone else points',
            'I draw the wrong conclusion from {beat} and waste an hour',
        ],
    },
    'Medicine': {
        'Success': [
            'I stabilize the patient while the rest of the room can not stop watching {beat}',
            'I work fast and clean, ignoring {beat} until the bleeding stops',
            'I keep them conscious and talking, using {beat} to hold their focus off the pain',
            'I bind and brew with steady hands while {beat} keeps the crowd busy',
        ],
        'Failure': [
            'I fumble the treatment, distracted by {beat} at exactly the wrong second',
            'My hands shake and the patient worsens while I keep glancing at {beat}',
            'I misjudge the wound with half my attention stuck on {beat}',
            'I run short on supplies and time, and {beat} is not helping anyone',
        ],
    },
    'Nature': {
        'Success': [
            'I read {beat} as a sign of what the land is doing and warn the party',
            'I identify the plant or beast tied to {beat} before anyone eats or steps wrong',
            'I predict weather or terrain trouble from {beat} and reroute us',
            'I hear the quiet around {beat} and know predators are close',
        ],
        'Failure': [
            'I misread {beat} as harmless and nearly poison us with confidence',
            'I ignore the sign in {beat} until we are already in trouble',
            'I confuse what {beat} means and choose the wrong path',
        ],
    },
    'Perception': {
        'Success': [
            'I spot {beat} before anyone else reacts',
            'Something about {beat} catches my eye before the surprise becomes real',
            'I catch the wrong note around {beat} and raise the alarm',
            'I notice {beat} because I notice everything when I am bored',
            'Movement tied to {beat} gives away the ambush early',
            'I smell trouble in {beat} before {who} finish their sentence',
        ],
        'Failure': [
            'I walk past {beat} without seeing it—my wings were not even in the way',
            'I miss the warning in {beat} until it is almost too late',
            'I scan the area and report all clear despite {beat} screaming otherwise',
            'I stare at {beat} and still overlook what matters',
        ],
    },
    'Performance': {
        'Success': [
            'I turn {beat} into the setup for a bit that wins the room',
            'I riff on {beat} until {audience} are laughing or crying on cue',
            'I recover from a stumble near {beat} so smoothly it looks intentional',
            'I finish the set referencing {beat} and leave them buzzing',
        ],
        'Failure': [
            'I try to joke about {beat} and the room dies before the second line',
            'I trip over {beat} mid-act and never recover my rhythm',
            'I misread the mood around {beat} and bomb like I skipped rehearsal',
        ],
    },
    'Persuasion': {
        'Success': [
            'I win {negotiator} over while {beat} hangs in the air between us',
            'I talk us out of trouble without threats, never flinching at {beat}',
            'I find the argument that moves {negotiator} even with {beat} fraying nerves',
            'I turn flat resistance into reluctant cooperation before {beat} sours the mood',
        ],
        'Failure': [
            'My pitch lands flat and {beat} hands {negotiator} a reason to walk',
            'I push too hard while {beat} sets everyone on edge and close the door myself',
            'I misjudge what {negotiator} wants and {beat} buries the rest of my point',
        ],
    },
    'Religion': {
        'Success': [
            'I recall {doctrine} that applies to {beat} before we offend someone holy',
            'I recognize the rite tied to {beat} and perform it correctly',
            'I interpret the omen in {beat} with sacred texts, not wild guesses',
            'I calm {who} with the right prayer when spooked by {beat}',
        ],
        'Failure': [
            'I misquote scripture about {beat} and get corrected harshly',
            'I confuse two faiths regarding {beat} and offend {who}',
            'I treat {beat} casually and regret it when the air turns judgmental',
        ],
    },
    'Sleight of Hand': {
        'Success': [
            'My hands move faster than {who} can follow, using {beat} as cover',
            'I lift or swap something by {beat} without a flicker of suspicion',
            'I plant {evidence} near {beat} smoothly enough to worry myself',
            'I cheat or palm while everyone watches {beat} instead of me',
        ],
        'Failure': [
            'I drop something by {beat} and everyone sees—so much for subtlety',
            'I fumble near {beat} and get caught with my hands literally full',
            'My swap by {beat} is clumsy enough to end careers',
        ],
    },
    'Stealth': {
        'Success': [
            'I use {beat} as cover and pass {guard} without a glance',
            'I hold still, letting {beat} pull attention elsewhere until the path clears',
            'I cross the space by {beat} leaving no sign I was there',
            'I slip past the danger at {beat} on silent feet',
        ],
        'Failure': [
            'I kick something by {beat} and the noise gives me away',
            'I step into the light near {beat} like a spotlight found me',
            'I thought {beat} hid me—it did not, and everyone agrees',
        ],
    },
    'Survival': {
        'Success': [
            'I read {beat} as a trail sign and choose the safer route',
            'I find shelter or water because {beat} told me where to look',
            'I predict trouble from {beat} and reroute before we pay for it',
            'I rig camp or fire despite {beat} making it harder',
        ],
        'Failure': [
            'I misread {beat} and lead us astray with confident wrongness',
            'I ignore the warning in {beat} until we are cold, lost, or both',
            'I choose poorly because of {beat} and we pay in morale',
        ],
    },
}


def flavor_lines_for(scene_id, skill, suffix, ctx, line_is_valid_fn, limit=18):
    """Build unique beat-driven lines for a scene/skill/outcome."""
    beats = SCENE_BEATS.get(scene_id, SCENE_BEATS.get('Village', []))
    templates = SKILL_BEAT_TEMPLATES.get(skill, {}).get(suffix, [])
    if not beats or not templates:
        return []

    lines = []
    for beat in beats:
        for template in templates:
            fmt = dict(ctx)
            fmt['beat'] = beat
            try:
                line = template.format(**fmt)
            except KeyError:
                continue
            if line in lines:
                continue
            if line_is_valid_fn(skill, line):
                lines.append(line)
            if len(lines) >= limit:
                return lines
    return lines
