"""Wittier, Blingus-voiced skill templates for scene outcome generation."""

SKILL_TEMPLATES = {
    'Acrobatics': {
        'Success': [
            "I cross {obstacle} in {place} with a flourish and stick the landing like I planned the applause",
            "I bounce off {foothold} in {where}, spin once for no reason, and land grinning at {who}",
            "I recover from a slip in {place} so smoothly {who} think it was choreography",
            "I weave through {place} while {who} stare like I just sold tickets to my own stunt show",
            "I balance on {foothold} with empty hands raised—ta-da—and hop down before gravity argues",
            "I flip over {obstacle} in {place} and land on my feet without breaking stride or dignity",
            "I catch myself on {foothold} mid-fall, bow, and pretend the stumble was the bit",
            "I move through {place} in half the time anyone expected, humming like this is easy",
        ],
        'Failure': [
            "I misjudge {obstacle} in {place} and hit the ground with the grace of a dropped lute",
            "My foot catches on {foothold} and I tumble in front of {who}—the room gets a free show",
            "I attempt a showy move in {place} and eat dirt while my wings flutter uselessly",
            "I lose my balance on {obstacle} and crash into something loud enough to start rumors",
            "My acrobatics fail me in {where} and the landing is aggressively undignified",
            "I try to look graceful on {foothold} and faceplant so hard {who} wince in sympathy",
            "I slip on {obstacle} and take {who} down with me like a badly timed duet",
            "My leap in {place} falls short and everyone pretends not to laugh— poorly",
        ],
    },
    'Animal Handling': {
        'Success': [
            "I coax {animal} in {place} with slow hands and the kind of voice I use on skittish audiences",
            "I offer {treat} and wait until {animal} takes it without biting or judging my life choices",
            "I read panic in {animal2} before it spooks and adjust like I've done this on tour",
            "I guide {animal} away from {beast_trouble} without anyone losing a finger or dignity",
            "I speak low and steady until {animal2} stops pacing and lies down like it trusts me",
            "I keep my body small near {animal} until trust wins out over instinct",
            "I calm {animal} in {place} well enough that {who} stop backing away from the drama",
            "I handle {animal2} exactly right and the immediate chaos downgrades to a story later",
        ],
        'Failure': [
            "I move too fast and {animal} bolts straight into {beast_trouble} like I planned chaos",
            "I misread {animal2} and nearly take a bite for assuming charisma works on teeth",
            "I reach for {animal} too quickly and it lashes out like I insulted its ancestors",
            "I offer {treat} at the worst moment and make {animal} more agitated than before",
            "I miss how frightened {animal} looks and startle it into legend-worthy noise",
            "My attempt with {animal2} in {place} turns into a slapstick routine nobody asked for",
            "I speak too loud near {animal} and every beast nearby panics on cue",
            "I grab at {animal} at the wrong moment and lose its trust—and a little pride",
        ],
    },
    'Arcana': {
        'Success': [
            "I recognize {aura} in {place} and name the spell before {who} poke it with a stick",
            "I trace {rune} and explain its purpose like I'm reviewing a bad chorus structure",
            "I identify the school of magic on {ward} and tell {who} exactly what not to touch",
            "I read {magic} in {where} and warn the party with the confidence of a critic who cares",
            "I sense the enchantment on {ward} and how to avoid triggering a very bad second verse",
            "I decode {rune} in {place} and piece together the caster's intent—mostly petty, honestly",
            "I spot unstable magic around {magic} and know how to dispel it without theatrics",
            "I name the components from {aura} alone and sound insufferably pleased about it",
        ],
        'Failure': [
            "The symbols on {rune} in {place} might as well be tavern graffiti to me today",
            "I misidentify {magic} in {where} and almost get us cursed for my confidence",
            "I touch {ward} thinking it's harmless and learn the universe has opinions",
            "I can't parse {aura} in {where} no matter how hard I squint like a diva at bad lighting",
            "My theory about {magic} is wrong and {who} pay for my educated guess",
            "I confuse two schools of magic on {rune} and give advice that would fail a cantrip exam",
            "The enchantment on {ward} stays a mystery and keeps humming like it's laughing at me",
            "I misread {aura} in {place} and nearly trigger something with worse reviews than my early work",
        ],
    },
    'Athletics': {
        'Success': [
            "I haul myself up {climb} in {place} with strength to spare and a complaint ready for later",
            "I push through {obstacle} in {where} when others hesitate like the door owes me money",
            "I lift {lift} clear of {who} before anyone gets crushed or embarrassed on my watch",
            "I climb {climb} fast enough to beat the danger and still comment on the view",
            "I hold the line in {place} when the strain should break me—stubbornness counts as athletics",
            "I swim, climb, or sprint through {where} and refuse to quit with audience energy",
            "I break {lift} free with brute force that finally works and a grunt worth the tale",
            "I leap {gap} in {place} and catch the far side cleanly, wings fluttering for style points",
        ],
        'Failure': [
            "My grip fails on {climb} and I slide back down in {place} with all my dignity trailing behind",
            "I strain against {lift} and can't budge it—turns out fairy strength has limits",
            "I misjudge {gap} in {where} and fall short in a way {who} will describe for weeks",
            "My muscles give out in {place} at the worst possible moment, naturally",
            "I try to climb {climb} and slip, scraping hands, pride, and maybe a buckle",
            "I overestimate my strength on {lift} and drop it like a bad note at the finale",
            "I exhaust myself on {obstacle} and need {who} to pull me out of my own hero moment",
            "I attempt the feat in {where} and fail loudly enough to attract the wrong attention",
        ],
    },
    'Deception': {
        'Success': [
            "I sell {lie} in {place} with a straight face and the timing of a born storyteller",
            "I invent a cover story in {where} that holds under scrutiny and mild applause",
            "I misdirect {mark} using {distraction} while the truth sneaks out the side door",
            "I play the part in {place} so well even I almost believe my own press release",
            "I answer the hard question in {where} without a tell—years of bardic training help",
            "I weave {lie} around {mark} and send attention the wrong way like a good hook",
            "I convince {mark} I'm someone I'm not, at least until the next inconvenient question",
            "I redirect the conversation in {place} before anyone connects dots I'd rather keep loose",
        ],
        'Failure': [
            "My story in {place} falls apart the moment someone asks a follow-up I didn't rehearse",
            "I stammer near {mark} and {who} know something's off—my wings give me away",
            "I contradict {lie} in {where} and the deception collapses like a cheap stage flat",
            "My nervous glance at {mark} gives everything away including my hope",
            "I try to bluff {mark} in {place} and get laughed at by the wrong people",
            "I forget a detail in {lie} and get caught cold with no encore prepared",
            "My cover in {where} lasts about ten seconds—record even for me",
            "I lie badly in {place} and make {who} more suspicious than a bard with too many secrets",
        ],
    },
    'History': {
        'Success': [
            "I recall exactly who ruled {place} and why that matters now—history is just gossip with dates",
            "I recognize {relic} and tell the story behind it like I'm introducing an old hit",
            "I connect {inscription} in {where} to {era} that {who} forgot on purpose",
            "I remember the old treaty that explains the tension in {place} and everyone's bad mood",
            "I identify the era of {relic} from craftsmanship alone and look insufferably smug",
            "I cite {era} and what went wrong the last time—spoiler: similarly",
            "I know the legend tied to {inscription} and warn the party before the refrain repeats",
            "I translate {inscription} without guessing, which is rare and I mention it",
        ],
        'Failure': [
            "I swear I've read about {place} but can't recall a useful detail under pressure",
            "I misdate {relic} by centuries and {who} notice like I'm off-key on the chorus",
            "I confuse two wars in {where} and draw the wrong lesson with full confidence",
            "The {inscription} might as well be gibberish and my wings droop a little",
            "I guess at who built {place} and guess wrong in front of an audience",
            "I mix up legends about {era} and steer us like a bard who skipped rehearsal",
            "I blank on the name {who} expected me to know and smile through the silence",
            "I invent a historical fact about {relic} that gets corrected immediately and painfully",
        ],
    },
    'Insight': {
        'Success': [
            "I catch {tell} from {subject} in {place} and know what they really want",
            "I sense {subject} is lying in {where} before anyone else catches on",
            "I notice how {subject} reacts when the conversation turns risky",
            "I understand {motive} from {subject} before it boils over into something dramatic",
            "I read {subject} well enough in {place} to change my approach in time",
            "I realize {subject} is scared, not angry, and adjust like a professional",
            "I see who among {who} is holding back the truth",
            "I hear hesitation when {subject} speaks in {where} and know the story does not fit",
        ],
        'Failure': [
            "I trust {subject} in {place} and miss the warning signs written in neon, basically",
            "I read {subject} completely wrong in {where} and advise the party into comedy",
            "I think {who} are friendly and walk into a setup with my best smile on",
            "I miss the fear behind the bravado from {subject} until it is inconvenient",
            "I assume honesty from {subject} in {place} and get played like a cheap fiddle",
            "I misread silence from {subject} as agreement—it was not",
            "I do not notice the lie from {subject} until the punchline lands on us",
            "I misjudge {motive} from {subject} in {where} and advise the party badly",
        ],
    },
    'Intimidation': {
        'Success': [
            "I lower my voice in {place} and {mark} reconsider like I might review them publicly",
            "I make {threat} in {where} feel real without raising a hand—presence is a weapon too",
            "I stare down {mark} until they step aside and wonder why they're sweating",
            "I use {leverage} as pressure and {who} back off before the bit gets ugly",
            "I project enough menace in {place} that talk replaces action—cheap and effective",
            "I convince {mark} I'm not bluffing about {beast_trouble} or worse, my mood",
            "I turn the mood in {place} cold and get compliance without a second verse",
            "I let silence do the work in {where} until {mark} breaks like a bad note",
        ],
        'Failure': [
            "I try to intimidate {mark} in {place} and they laugh—fair, I'm small and sparkly",
            "My {threat} in {where} lands like a lullaby with aggressive eye contact",
            "I attempt menace near {mark} and look more annoyed fairy than terrifying",
            "I bark orders in {place} and {who} ignore me like background music",
            "I overplay the act in {where} and lose credibility faster than a heckler wins",
            "I threaten {mark} who clearly isn't impressed by wings and sarcasm",
            "My voice cracks in {place} at the worst moment—ruins the whole intimidation chorus",
            "I bluff about {leverage} and get called on it in front of {who}",
        ],
    },
    'Investigation': {
        'Success': [
            "I find {clue} in {where} that everyone else walked past like bad lyrics in a draft",
            "I connect {evidence} to {hidden} and the picture clears like a final chorus",
            "I search {where} methodically and turn up what we need without theatrics",
            "I notice what's missing in {place}, not just what's present—absence is a clue too",
            "I reconstruct events in {where} from {evidence} and timing like a detective bard",
            "I follow {clue} to {hidden} without disturbing the scene or my reputation",
            "I ask the right question in {place} and {who} answer too much, as usual",
            "I piece together {clue} and {evidence} into one answer worth a song someday",
        ],
        'Failure': [
            "I search {place} thoroughly and find nothing useful except my own frustration",
            "I miss {clue} in {where} that was right in front of me—humbling",
            "I follow a false lead from {evidence} and waste time I could've spent performing",
            "I contaminate the scene in {place} and ruin what was left like a clumsy encore",
            "I draw the wrong conclusion from {clue} and steer us into the wrong act",
            "I overlook {hidden} that {who} catch later and remind me about",
            "I can't make {evidence} fit any theory that works—my brain refuses the melody",
            "I get distracted in {where} and lose the thread like a bard between verses",
        ],
    },
    'Medicine': {
        'Success': [
            "I diagnose {symptom} in {patient} in {place} and know the treatment—not my usual gig, but fine",
            "I stabilize {injury} near {who} before it worsens into a ballad nobody wants",
            "I recognize poison in {symptom} and act fast before the drama escalates",
            "I clean and bind {injury} with what we have and a steady hand I'm surprised to own",
            "I keep {patient} conscious in {where} until proper help arrives or I run out of jokes",
            "I spot infection early in {injury} and stop it spreading—small victory, big relief",
            "I set the bone, stitch the cut, or brew the draught that works and accept surprised applause",
            "I talk {patient} through shock in {place} until color returns and panic fades",
        ],
        'Failure': [
            "I misdiagnose {symptom} in {patient} in {place} and treat the wrong thing—classic",
            "I fumble the bandage on {injury} and cause more pain than the original injury",
            "I can't tell poison from exhaustion in {symptom} and guess with confidence",
            "My hands shake in {where} and {patient} worsens while I wish I were singing instead",
            "I apply the wrong remedy to {injury} and regret it immediately and loudly",
            "I miss the internal damage to {patient} until it's obvious to everyone but me",
            "I try to help {patient} and make the bleeding worse—wrong skill, wrong day",
            "I lack supplies in {place} and can't do enough for {injury} despite my best bit",
        ],
    },
    'Nature': {
        'Success': [
            "I identify {flora} in {where} instantly and know if it's lunch or a mistake",
            "I read {fauna} sign in {terrain_nat} and know what's nearby before it introduces itself",
            "I recognize {weather} over {place} before it ruins everyone's hair",
            "I explain {flora} to {who} before anyone eats the wrong thing and writes a complaint",
            "I predict danger from {fauna} in {where} and reroute us like a sensible headliner",
            "I know which path through {terrain_nat} won't collapse, flood, or embarrass us",
            "I spot the venomous look-alike among {flora} and warn the party with authority",
            "I hear {fauna} go quiet in {place} and know predators are close—nature's bad preview",
        ],
        'Failure': [
            "I misidentify {flora} in {where} and nearly poison us with confidence",
            "I read {fauna} sign wrong in {terrain_nat} and choose a route worth a tragic ballad",
            "I dismiss {weather} signs in {where} and we pay for it like an unpaid bar tab",
            "I touch the wrong {flora} and itch for hours while {who} try not to comment",
            "I underestimate {fauna} near {place} and learn animals don't care about my reputation",
            "I confuse edible and toxic {flora} in {where}—survival is not my genre",
            "I ignore {whose} warnings and trust bad nature lore because I'm stubborn",
            "The wilds around {place} outsmart my knowledge today and I'm humble about it",
        ],
    },
    'Perception': {
        'Success': [
            "I spot {hidden_thing} in {place} before anyone else—including whoever hid it badly",
            "I hear {noise} in {where} that doesn't belong like a wrong note in a quiet song",
            "I catch movement in {shadow} near {who} before the surprise party becomes real",
            "I notice the trap, peephole, or pickpocket in {place} because I notice everything when bored",
            "I see what's wrong with {evidence} while {who} chat about nothing important",
            "I smell {scent} in {where} first and raise the alarm before the punchline hits",
            "I find {clue} near {hidden} before it's gone with the next distraction",
            "I watch {mark} in {place} and catch the tell that says they're lying or stealing",
        ],
        'Failure': [
            "I walk past {hidden_thing} in {place} without seeing it—my wings weren't even in the way",
            "I miss the ambush setup in {where} until it's almost too late for comfort",
            "I don't hear {noise} approaching in {place} because I was thinking about a better rhyme",
            "I stare at {evidence} and still overlook {hidden} like a bad lighting cue",
            "I'm distracted in {place} and {who} notice first—mortifying for a scout bard",
            "I fail to spot {mark} watching us from {shadow} until they want to be seen",
            "I miss {scent} that should've warned us in {where} and feel foolish when told",
            "I scan {place} and report all clear — incorrectly, and with confidence",
        ],
    },
    'Performance': {
        'Success': [
            "I command {audience} in {place} from the first note like the room owes me rent",
            "I turn {where} into {stage} and own it for one set they'll quote badly later",
            "I deliver {act} near {stage} like it was built for me and my ridiculous confidence",
            "I recover a flub in {where} so smoothly it looks intentional—years of practice",
            "I finish strong in {place} and {audience} erupt like I hit the high note on purpose",
            "I match the mood of {place} and elevate it one verse at a time",
            "I win laughs, tears, or silence from {audience} exactly when I mean to—chef's kiss",
            "I leave {where} buzzing about {act} and maybe buying drinks",
        ],
        'Failure': [
            "My {act} in {place} dies before the second verse and takes my ego with it",
            "I forget my lines on {stage} and stall badly enough to hear crickets think",
            "I misread {audience} in {where} and bomb like a bard who skipped rehearsal",
            "I trip over {obstacle} mid-act and never recover my rhythm or dignity",
            "I play to {audience} who clearly aren't interested in my key or my face",
            "My voice cracks in {place} at the worst moment—tragic and audible",
            "I attempt grandeur on {stage} and get pity applause that hurts worse",
            "The room in {where} stays painfully quiet like I forgot how songs work",
        ],
    },
    'Persuasion': {
        'Success': [
            "I find the exact argument that moves {negotiator} in {place}—charm is a skill, not luck",
            "I appeal with {pitch} in {where} and win without threats or visible sweating",
            "I talk {negotiator} into the sensible choice and make them think it was their idea",
            "I negotiate with {offer} near {who} and both sides feel heard, somehow",
            "I reframe the situation so {negotiator} sees our side like a better chorus",
            "I keep my tone warm in {place} and get agreement before pride kicks in",
            "I persuade {negotiator} to help us when others failed—add it to my legend",
            "I turn resistance in {where} into reluctant cooperation and a grudging smile",
        ],
        'Failure': [
            "My pitch to {negotiator} in {place} lands flat like a joke without a punchline",
            "I push too hard in {where} and close the door with my own enthusiasm",
            "I misjudge what {negotiator} cares about and talk about the wrong thing beautifully",
            "I argue with {who} instead of persuading them—classic bard mistake",
            "I sound desperate in {place} and lose leverage along with my cool",
            "I fail to read the room in {where} and step on toes in four-part harmony",
            "I make promises to {negotiator} nobody believes, including me",
            "I convince nobody in {place} despite my best speech and my best smile",
        ],
    },
    'Religion': {
        'Success': [
            "I recall the {doctrine} that applies in {place} before we offend someone holy",
            "I recognize the rite tied to {shrine} and perform it correctly—rare sober moment",
            "I explain the omen at {shrine} using sacred texts instead of wild guesses",
            "I identify the deity's symbol in {place} and its meaning without embarrassing us",
            "I calm {who} with the right prayer at {shrine} like a lullaby with stakes",
            "I know which taboo we're near in {place} and avoid offense like a professional guest",
            "I interpret {inscription} on {shrine} accurately and resist adding a joke—mostly",
            "I cite {doctrine} in {where} and {negotiator} listens like I'm credible",
        ],
        'Failure': [
            "I misquote {doctrine} in {place} and get corrected harshly by someone with better memory",
            "I confuse two faiths in {where} and offend {who} with creative enthusiasm",
            "I can't remember the rite for {shrine} and improvise badly",
            "I misread the omen at {shrine} completely and steer us toward irony",
            "I guess at {doctrine} in {place} and guess wrong with bardic confidence",
            "I treat {shrine} casually and regret it when the air gets judgmental",
            "I fail to recognize the symbol on {relic} and look like a tourist",
            "I draw blank on scripture when {negotiator} asks—my wings shrink a little",
        ],
    },
    'Sleight of Hand': {
        'Success': [
            "My hands move faster than {who} can follow in {place}—misdirection is an art form",
            "I palm {item} near {mark} without a flicker of suspicion or guilt, mostly",
            "I swap {item} for the decoy in {where} cleanly like a magician with better patter",
            "I lift from {mark} while they watch {distraction}—classic, still works",
            "I tie, untie, or pick {hidden} in {where} before anyone notices the missing beat",
            "I plant {evidence} on {mark} in {place} smoothly enough to worry myself",
            "I cheat at cards while {audience} watch the wrong hand—poetry in motion",
            "I conceal {item} in {pocket} until the perfect moment and a tiny smirk",
        ],
        'Failure': [
            "I drop {item} in {place} and everyone sees—so much for subtlety",
            "I fumble near {mark} and get caught cold with my hands literally full",
            "My swap in {where} is clumsy and obvious enough to end careers",
            "I snag my sleeve mid-trick in {place} and the bit becomes physical comedy",
            "I move too slow near {mark} and get called out by someone who wasn't even trying",
            "I misjudge {whose} attention and reveal both hands like a bad finale",
            "I try to lift from {mark} and they feel everything—including my shame",
            "My sleight in {place} becomes a public embarrassment with witnesses",
        ],
    },
    'Stealth': {
        'Success': [
            "I move through {place} without adding to {noise} like silence is my backup singer",
            "I use {shadow} and {cover_stealth} to stay unseen—small helps in tight spaces",
            "I pass behind {guard} in {where} and nobody turns; my wings tuck like I planned it",
            "I reach {hidden} and back away unnoticed, already composing the story",
            "I hold still in {cover_stealth} until {guard} moves on, barely breathing",
            "I slip past {guard} in {where} on silent feet and unreasonable confidence",
            "I blend into {shadow} until I become part of the background scenery",
            "I cross {place} leaving no sign I was there except maybe good gossip later",
        ],
        'Failure': [
            "I kick {item} in {place} and the noise gives me away like a cymbal in a lullaby",
            "I step into {light} in {where} like a spotlight found me on purpose",
            "I stumble on {obstacle} and {guard} turn instantly—grace exits stage left",
            "My gear clinks in {where} and ruins everything including my reputation",
            "I try to hide in {cover_stealth} and {guard} point right at my sparkly self",
            "I misjudge {shadow} and stand out worse than a solo at a funeral",
            "I sneeze or curse in {place} at the worst time—biology hates stealth",
            "I thought I was hidden in {shadow} — I wasn't, and everyone agrees",
        ],
    },
    'Survival': {
        'Success': [
            "I read {trail} in {terrain_nat} and choose the path that won't kill the mood or us",
            "I find {shelter} in {place} before weather turns lethal or melodramatic",
            "I start a fire in {where} with stubborn materials and unreasonable optimism",
            "I locate {forage} or water when supplies run low and morale lower",
            "I rig {shelter} from what {place} offers and keep {who} alive and complaining less",
            "I predict {weather} in {where} and avoid it early like a bard dodging a bad gig",
            "I navigate {terrain_nat} without getting turned around—rare and worth mentioning",
            "I preserve supplies in {place} when options are thin and jokes are thinner",
        ],
        'Failure': [
            "I misread {trail} in {terrain_nat} and lead us astray with confident wrongness",
            "I can't get a fire going in {place} despite trying and cursing poetically",
            "I choose the wrong camp in {where} and we pay for it in cold and regret",
            "I waste hours in {terrain_nat} chasing a false {trail} like a bad rumor",
            "I eat the wrong {forage} and feel it later in ways performance can't fix",
            "I ignore signs of {weather} in {place} until we're in trouble and I'm out of quips",
            "I lose the path in {where} and panic sets in among {who}",
            "The wilds around {place} beat my survival instincts today—humbling and damp",
        ],
    },
}
